name: raft_flutter_workspace
publish_to: none
environment:
  sdk: ^3.13.5
workspace:
  - apps/raft_flutter
  - packages/raft_ui
  - packages/raft_client
  - packages/raft_sync
  - packages/flutter_chat_ui
  - packages/super_sliver_list
  - tool/ds_audit
