// Generated from pinned shared RUNTIME_MODELS. Regenerate with generate_catalog.ts.
const sourceRuntimeModelLabels = <String, Map<String, String>>{
  'external': {'external': 'External agent'},
  'builtin': {
    'deepseek/deepseek-v4-pro': 'DeepSeek V4 Pro',
    'deepseek/deepseek-flash': 'DeepSeek V4.1 Flash',
    'minimax/MiniMax-M3': 'MiniMax-M3',
    'minimax/MiniMax-M2.7': 'MiniMax-M2.7',
    'minimax/MiniMax-M2.7-highspeed': 'MiniMax-M2.7-highspeed',
    'minimax-cn/MiniMax-M3': 'MiniMax-M3',
    'minimax-cn/MiniMax-M2.7': 'MiniMax-M2.7',
    'minimax-cn/MiniMax-M2.7-highspeed': 'MiniMax-M2.7-highspeed',
    'zai/glm-5.3': 'GLM-5.3',
    'zai/glm-5.2': 'GLM-5.2',
    'zai/glm-4.7': 'GLM-4.7',
    'zai/glm-5.3-highspeed': 'GLM-5.3 Highspeed',
    'zai/glm-5.3-flash': 'GLM-5.3-Flash',
    'zai/glm-5.2-highspeed': 'GLM-5.2 Highspeed',
    'zai/glm-5-turbo': 'GLM-5-Turbo',
    'zai-coding-cn/glm-5.3': 'GLM-5.3',
    'zai-coding-cn/glm-4.6v': 'GLM-4.6V',
    'zai-coding-cn/glm-5.3-highspeed': 'GLM-5.3 Highspeed',
    'zai-coding-cn/glm-5.3-flash': 'GLM-5.3-Flash',
    'moonshotai/kimi-k2.7-code': 'Kimi K2.7 Code',
    'moonshotai/kimi-k2.7-code-highspeed': 'Kimi K2.7 Code HighSpeed',
    'moonshotai/kimi-k3': 'Kimi K3',
    'moonshotai/kimi-k2.6': 'Kimi K2.6',
    'moonshotai-cn/kimi-k2.7-code': 'Kimi K2.7 Code',
    'moonshotai-cn/kimi-k2.7-code-highspeed': 'Kimi K2.7 Code HighSpeed',
    'moonshotai-cn/kimi-k3': 'Kimi K3',
    'moonshotai-cn/kimi-k2.6': 'Kimi K2.6',
    'kimi-coding/k3-256k': 'Kimi K3-256K',
    'kimi-coding/k3': 'Kimi K3',
    'kimi-coding/kimi-for-coding': 'kimi-for-coding',
    'kimi-coding/kimi-for-coding-highspeed': 'Kimi For Coding HighSpeed',
    'qwen-token-plan/deepseek-v4-pro-0813': 'DeepSeek V4 Pro 0813',
    'qwen-token-plan/deepseek-v4-pro': 'DeepSeek V4 Pro',
    'qwen-token-plan/qwen3.8-max': 'Qwen3.8 Max',
    'qwen-token-plan/qwen3.7-max': 'Qwen3.7 Max',
    'qwen-token-plan/kimi-k2.7-code': 'Kimi K2.7 Code',
    'qwen-token-plan/glm-5.3': 'GLM-5.3',
    'qwen-token-plan/glm-5.2': 'GLM-5.2',
    'qwen-token-plan/glm-5.1': 'GLM-5.1',
    'qwen-token-plan/glm-5': 'GLM-5',
    'qwen-token-plan/qwen3.7-plus': 'Qwen3.7 Plus',
    'qwen-token-plan/qwen3.6-plus': 'Qwen3.6 Plus',
    'qwen-token-plan/deepseek-v3.2': 'DeepSeek V3.2',
    'qwen-token-plan/kimi-k2.6': 'Kimi K2.6',
    'qwen-token-plan/kimi-k2.5': 'Kimi K2.5',
    'qwen-token-plan/MiniMax-M2.5': 'MiniMax-M2.5',
    'qwen-token-plan/deepseek-v4-flash-0731': 'DeepSeek V4 Flash 0731',
    'qwen-token-plan/deepseek-v4.1-flash': 'DeepSeek V4.1 Flash',
    'qwen-token-plan/deepseek-v4-flash': 'DeepSeek V4 Flash',
    'qwen-token-plan/qwen3.8-flash': 'Qwen3.8 Flash',
    'qwen-token-plan/qwen3.6-flash': 'Qwen3.6 Flash',
    'qwen-token-plan-cn/deepseek-v4-pro-0813': 'DeepSeek V4 Pro 0813',
    'qwen-token-plan-cn/deepseek-v4-pro': 'DeepSeek V4 Pro',
    'qwen-token-plan-cn/qwen3.8-max': 'Qwen3.8 Max',
    'qwen-token-plan-cn/qwen3.7-max': 'Qwen3.7 Max',
    'qwen-token-plan-cn/kimi-k2.7-code': 'Kimi K2.7 Code',
    'qwen-token-plan-cn/glm-5.3': 'GLM-5.3',
    'qwen-token-plan-cn/glm-5.2': 'GLM-5.2',
    'qwen-token-plan-cn/glm-5.1': 'GLM-5.1',
    'qwen-token-plan-cn/glm-5': 'GLM-5',
    'qwen-token-plan-cn/qwen3.7-plus': 'Qwen3.7 Plus',
    'qwen-token-plan-cn/qwen3.6-plus': 'Qwen3.6 Plus',
    'qwen-token-plan-cn/deepseek-v3.2': 'DeepSeek V3.2',
    'qwen-token-plan-cn/kimi-k2.6': 'Kimi K2.6',
    'qwen-token-plan-cn/kimi-k2.5': 'Kimi K2.5',
    'qwen-token-plan-cn/MiniMax-M2.5': 'MiniMax-M2.5',
    'qwen-token-plan-cn/deepseek-v4-flash-0731': 'DeepSeek V4 Flash 0731',
    'qwen-token-plan-cn/deepseek-v4.1-flash': 'DeepSeek V4.1 Flash',
    'qwen-token-plan-cn/deepseek-v4-flash': 'DeepSeek V4 Flash',
    'qwen-token-plan-cn/qwen3.8-flash': 'Qwen3.8 Flash',
    'qwen-token-plan-cn/qwen3.6-flash': 'Qwen3.6 Flash',
    'openrouter/anthropic/claude-fable-5.1': 'Anthropic: Claude Fable 5.1',
    'openrouter/anthropic/claude-fable-5.1:batch':
        'Anthropic: Claude Fable 5.1 (batch)',
    'openrouter/anthropic/claude-fable-5': 'Anthropic: Claude Fable 5',
    'openrouter/anthropic/claude-fable-5:batch':
        'Anthropic: Claude Fable 5 (batch)',
    'openrouter/~anthropic/claude-fable-latest':
        'Anthropic: Claude Fable Latest',
    'openrouter/anthropic/claude-opus-5.5': 'Anthropic: Claude Opus 5.5',
    'openrouter/anthropic/claude-opus-5.5:batch':
        'Anthropic: Claude Opus 5.5 (batch)',
    'openrouter/anthropic/claude-opus-5': 'Anthropic: Claude Opus 5',
    'openrouter/anthropic/claude-opus-5:batch':
        'Anthropic: Claude Opus 5 (batch)',
    'openrouter/anthropic/claude-opus-4.8': 'Anthropic: Claude Opus 4.8',
    'openrouter/anthropic/claude-opus-4.8:batch':
        'Anthropic: Claude Opus 4.8 (batch)',
    'openrouter/anthropic/claude-opus-4.7': 'Anthropic: Claude Opus 4.7',
    'openrouter/anthropic/claude-opus-4.7:batch':
        'Anthropic: Claude Opus 4.7 (batch)',
    'openrouter/anthropic/claude-opus-4.6': 'Anthropic: Claude Opus 4.6',
    'openrouter/anthropic/claude-opus-4.6:batch':
        'Anthropic: Claude Opus 4.6 (batch)',
    'openrouter/anthropic/claude-opus-4.5': 'Anthropic: Claude Opus 4.5',
    'openrouter/anthropic/claude-opus-4.5:batch':
        'Anthropic: Claude Opus 4.5 (batch)',
    'openrouter/anthropic/claude-opus-4.1': 'Anthropic: Claude Opus 4.1',
    'openrouter/anthropic/claude-opus-4.1:batch':
        'Anthropic: Claude Opus 4.1 (batch)',
    'openrouter/~anthropic/claude-opus-latest': 'Anthropic: Claude Opus Latest',
    'openrouter/anthropic/claude-sonnet-5.5': 'Anthropic: Claude Sonnet 5.5',
    'openrouter/anthropic/claude-sonnet-5.5:batch':
        'Anthropic: Claude Sonnet 5.5 (batch)',
    'openrouter/anthropic/claude-sonnet-5': 'Anthropic: Claude Sonnet 5',
    'openrouter/anthropic/claude-sonnet-5:batch':
        'Anthropic: Claude Sonnet 5 (batch)',
    'openrouter/anthropic/claude-sonnet-4.6': 'Anthropic: Claude Sonnet 4.6',
    'openrouter/anthropic/claude-sonnet-4.6:batch':
        'Anthropic: Claude Sonnet 4.6 (batch)',
    'openrouter/anthropic/claude-sonnet-4.5': 'Anthropic: Claude Sonnet 4.5',
    'openrouter/anthropic/claude-sonnet-4.5:batch':
        'Anthropic: Claude Sonnet 4.5 (batch)',
    'openrouter/anthropic/claude-sonnet-4': 'Anthropic: Claude Sonnet 4',
    'openrouter/~anthropic/claude-sonnet-latest':
        'Anthropic: Claude Sonnet Latest',
    'openrouter/anthropic/claude-haiku-4.5': 'Anthropic: Claude Haiku 4.5',
    'openrouter/anthropic/claude-haiku-4.5:batch':
        'Anthropic: Claude Haiku 4.5 (batch)',
    'openrouter/~anthropic/claude-haiku-latest':
        'Anthropic: Claude Haiku Latest',
    'openrouter/openai/gpt-5.1-codex-max': 'OpenAI: GPT-5.1-Codex-Max',
    'openrouter/kwaipilot/kat-coder-pro-v2.5': 'Kwaipilot: KAT-Coder-Pro V2.5',
    'openrouter/qwen/qwen3-max-thinking': 'Qwen: Qwen3 Max Thinking',
    'openrouter/qwen/qwen3.8-max-0902': 'Qwen: Qwen3.8 Max (0902)',
    'openrouter/deepseek/deepseek-v4-pro-0813':
        'DeepSeek: DeepSeek V4 Pro 0813',
    'openrouter/nvidia/nemotron-3-ultra-550b-a55b': 'NVIDIA: Nemotron 3 Ultra',
    'openrouter/deepseek/deepseek-v4-pro': 'DeepSeek: DeepSeek V4 Pro 0423',
    'openrouter/google/gemini-2.5-pro-preview':
        'Google: Gemini 2.5 Pro Preview 06-05',
    'openrouter/openai/gpt-6.1-sol-pro': 'OpenAI: GPT-6.1 Sol Pro',
    'openrouter/openai/gpt-6-astra-pro': 'OpenAI: GPT-6 Astra Pro',
    'openrouter/openai/gpt-6-astra-pro:batch':
        'OpenAI: GPT-6 Astra Pro (batch)',
    'openrouter/openai/gpt-6-luna-pro': 'OpenAI: GPT-6 Luna Pro',
    'openrouter/openai/gpt-6-luna-pro:batch': 'OpenAI: GPT-6 Luna Pro (batch)',
    'openrouter/openai/gpt-6-sol-pro': 'OpenAI: GPT-6 Sol Pro',
    'openrouter/openai/gpt-6-sol-pro:batch': 'OpenAI: GPT-6 Sol Pro (batch)',
    'openrouter/openai/gpt-5.6-luna-pro': 'OpenAI: GPT-5.6 Luna Pro',
    'openrouter/openai/gpt-5.6-luna-pro:batch':
        'OpenAI: GPT-5.6 Luna Pro (batch)',
    'openrouter/openai/gpt-5.6-sol-pro': 'OpenAI: GPT-5.6 Sol Pro',
    'openrouter/openai/gpt-5.6-sol-pro:batch':
        'OpenAI: GPT-5.6 Sol Pro (batch)',
    'openrouter/openai/gpt-5.6-terra-pro': 'OpenAI: GPT-5.6 Terra Pro',
    'openrouter/openai/gpt-5.6-terra-pro:batch':
        'OpenAI: GPT-5.6 Terra Pro (batch)',
    'openrouter/openai/gpt-5.5-pro': 'OpenAI: GPT-5.5 Pro',
    'openrouter/openai/gpt-5.5-pro:batch': 'OpenAI: GPT-5.5 Pro (batch)',
    'openrouter/openai/gpt-5.4-pro': 'OpenAI: GPT-5.4 Pro',
    'openrouter/openai/gpt-5.4-pro:batch': 'OpenAI: GPT-5.4 Pro (batch)',
    'openrouter/openai/gpt-5.2-pro': 'OpenAI: GPT-5.2 Pro',
    'openrouter/openai/gpt-5.2-pro:batch': 'OpenAI: GPT-5.2 Pro (batch)',
    'openrouter/openai/gpt-5-pro': 'OpenAI: GPT-5 Pro',
    'openrouter/openai/gpt-5-pro:batch': 'OpenAI: GPT-5 Pro (batch)',
    'openrouter/upstage/solar-pro4': 'Upstage: Solar Pro 4',
    'openrouter/qwen/qwen3.8-max-prime': 'Qwen: Qwen3.8 Max Prime',
    'openrouter/qwen/qwen3.7-max': 'Qwen: Qwen3.7 Max',
    'openrouter/qwen/qwen3.6-max-preview': 'Qwen: Qwen3.6 Max Preview',
    'openrouter/google/gemini-3.1-pro-preview':
        'Google: Gemini 3.1 Pro Preview',
    'openrouter/google/gemini-3.1-pro-preview:batch':
        'Google: Gemini 3.1 Pro Preview (batch)',
    'openrouter/google/gemini-3.1-pro-preview-customtools':
        'Google: Gemini 3.1 Pro Preview Custom Tools',
    'openrouter/openai/o3-pro': 'OpenAI: o3 Pro',
    'openrouter/qwen/qwen3-max': 'Qwen: Qwen3 Max',
    'openrouter/upstage/solar-pro-3': 'Upstage: Solar Pro 3',
    'openrouter/xiaomi/mimo-v2.6-pro': 'Xiaomi: MiMo-V2.6-Pro',
    'openrouter/xiaomi/mimo-v2.6-pro-ultraspeed':
        'Xiaomi: MiMo-V2.6-Pro-UltraSpeed',
    'openrouter/google/gemini-2.5-pro': 'Google: Gemini 2.5 Pro',
    'openrouter/google/gemini-2.5-pro:batch': 'Google: Gemini 2.5 Pro (batch)',
    'openrouter/nex-agi/nex-n2.5-pro': 'Nex AGI: Nex-N2.5-Pro',
    'openrouter/xiaomi/mimo-v2.5-pro': 'Xiaomi: MiMo-V2.5-Pro',
    'openrouter/sakana/fugu-ultra-v2': 'Sakana: Fugu Ultra v2',
    'openrouter/amazon/nova-premier-v1': 'Amazon: Nova Premier 1.0',
    'openrouter/amazon/nova-pro-v1': 'Amazon: Nova Pro 1.0',
    'openrouter/~deepseek/deepseek-pro-latest': 'DeepSeek: DeepSeek Pro Latest',
    'openrouter/~google/gemini-pro-latest': 'Google: Gemini Pro Latest',
    'openrouter/sakana/fugu-max': 'Sakana: Fugu Max',
    'openrouter/sakana/fugu-ultra': 'Sakana: Fugu Ultra',
    'openrouter/arcee-ai/trinity-large-thinking':
        'Arcee AI: Trinity Large Thinking',
    'openrouter/qwen/qwen3-coder': 'Qwen: Qwen3 Coder 480B A35B',
    'openrouter/qwen/qwen3-coder-30b-a3b-instruct':
        'Qwen: Qwen3 Coder 30B A3B Instruct',
    'openrouter/openai/gpt-5.3-codex': 'OpenAI: GPT-5.3-Codex',
    'openrouter/openai/gpt-5.2-codex': 'OpenAI: GPT-5.2-Codex',
    'openrouter/openai/gpt-5.1-codex': 'OpenAI: GPT-5.1-Codex',
    'openrouter/qwen/qwen3-coder-next': 'Qwen: Qwen3 Coder Next',
    'openrouter/qwen/qwen3-coder-plus': 'Qwen: Qwen3 Coder Plus',
    'openrouter/moonshotai/kimi-k2.7-code': 'MoonshotAI: Kimi K2.7 Code',
    'openrouter/bytedance-seed/seed-2.0-code': 'ByteDance Seed: Seed-2.0-Code',
    'openrouter/qwen/qwen3-235b-a22b-thinking-2507':
        'Qwen: Qwen3 235B A22B Thinking 2507',
    'openrouter/qwen/qwen3-30b-a3b-thinking-2507':
        'Qwen: Qwen3 30B A3B Thinking 2507',
    'openrouter/qwen/qwen3-vl-235b-a22b-thinking':
        'Qwen: Qwen3 VL 235B A22B Thinking',
    'openrouter/qwen/qwen3-next-80b-a3b-thinking':
        'Qwen: Qwen3 Next 80B A3B Thinking',
    'openrouter/qwen/qwen3-vl-30b-a3b-thinking':
        'Qwen: Qwen3 VL 30B A3B Thinking',
    'openrouter/qwen/qwen3-vl-8b-thinking': 'Qwen: Qwen3 VL 8B Thinking',
    'openrouter/google/gemini-3-pro-image':
        'Google: Nano Banana Pro (Gemini 3 Pro Image)',
    'openrouter/moonshotai/kimi-k2-thinking': 'MoonshotAI: Kimi K2 Thinking',
    'openrouter/thinkingmachines/inkling': 'Thinking Machines: Inkling',
    'openrouter/thinkingmachines/inkling-small':
        'Thinking Machines: Inkling Small',
    'openrouter/qwen/qwen3-coder-flash': 'Qwen: Qwen3 Coder Flash',
    'openrouter/mistralai/mistral-large-2512': 'Mistral: Mistral Large 3 2512',
    'openrouter/mistralai/mistral-large-2512:batch':
        'Mistral: Mistral Large 3 2512 (batch)',
    'openrouter/mistralai/mistral-large-2407': 'Mistral Large 2407',
    'openrouter/nvidia/nemotron-3-super-120b-a12b': 'NVIDIA: Nemotron 3 Super',
    'openrouter/mistralai/mistral-large': 'Mistral Large',
    'openrouter/nvidia/nemotron-3-ultra-550b-a55b:free':
        'NVIDIA: Nemotron 3 Ultra (free)',
    'openrouter/openai/gpt-5.1-codex-mini': 'OpenAI: GPT-5.1-Codex-Mini',
    'openrouter/qwen/qwen3.5-plus-20260420': 'Qwen: Qwen3.5 Plus 2026-04-20',
    'openrouter/mistralai/mistral-small-2603': 'Mistral: Mistral Small 4',
    'openrouter/mistralai/mistral-small-2603:batch':
        'Mistral: Mistral Small 4 (batch)',
    'openrouter/mistralai/devstral-2512': 'Mistral: Devstral 2 2512',
    'openrouter/mistralai/ministral-14b-2512': 'Mistral: Ministral 3 14B 2512',
    'openrouter/mistralai/ministral-3b-2512': 'Mistral: Ministral 3 3B 2512',
    'openrouter/mistralai/ministral-8b-2512': 'Mistral: Ministral 3 8B 2512',
    'openrouter/mistralai/ministral-8b-2512:batch':
        'Mistral: Ministral 3 8B 2512 (batch)',
    'openrouter/mistralai/codestral-2508': 'Mistral: Codestral 2508',
    'openrouter/mistralai/codestral-2508:batch':
        'Mistral: Codestral 2508 (batch)',
    'openrouter/mistralai/voxtral-small-24b-2507':
        'Mistral: Voxtral Small 24B 2507',
    'openrouter/qwen/qwen3-235b-a22b-2507':
        'Qwen: Qwen3 235B A22B Instruct 2507',
    'openrouter/qwen/qwen3-30b-a3b-instruct-2507':
        'Qwen: Qwen3 30B A3B Instruct 2507',
    'openrouter/qwen/qwen3.5-plus-02-15': 'Qwen: Qwen3.5 Plus 2026-02-15',
    'openrouter/qwen/qwen-plus-2025-07-28': 'Qwen: Qwen Plus 0728',
    'openrouter/openai/gpt-4o-2024-11-20': 'OpenAI: GPT-4o (2024-11-20)',
    'openrouter/openai/gpt-4o-2024-08-06': 'OpenAI: GPT-4o (2024-08-06)',
    'openrouter/openai/gpt-4o-2024-05-13': 'OpenAI: GPT-4o (2024-05-13)',
    'openrouter/moonshotai/kimi-k2-0905': 'MoonshotAI: Kimi K2 0905',
    'openrouter/moonshotai/kimi-k2': 'MoonshotAI: Kimi K2 0711',
    'openrouter/deepseek/deepseek-r1-0528': 'DeepSeek: R1 0528',
    'openrouter/qwen/qwen3.5-397b-a17b': 'Qwen: Qwen3.5 397B A17B',
    'openrouter/deepseek/deepseek-chat-v3-0324': 'DeepSeek: DeepSeek V3 0324',
    'openrouter/qwen/qwen3-235b-a22b': 'Qwen: Qwen3 235B A22B',
    'openrouter/qwen/qwen3-vl-235b-a22b-instruct':
        'Qwen: Qwen3 VL 235B A22B Instruct',
    'openrouter/openai/gpt-oss-120b': 'OpenAI: gpt-oss-120b',
    'openrouter/openai/gpt-oss-120b:batch': 'OpenAI: gpt-oss-120b (batch)',
    'openrouter/qwen/qwen3.8-2.4t-a95b': 'Qwen: Qwen3.8 2.4T A95B',
    'openrouter/qwen/qwen3-next-80b-a3b-instruct':
        'Qwen: Qwen3 Next 80B A3B Instruct',
    'openrouter/qwen/qwen-2.5-72b-instruct': 'Qwen2.5 72B Instruct',
    'openrouter/meta-llama/llama-3.1-70b-instruct':
        'Meta: Llama 3.1 70B Instruct',
    'openrouter/meta-llama/llama-3.3-70b-instruct':
        'Meta: Llama 3.3 70B Instruct',
    'openrouter/sao10k/l3.1-euryale-70b': 'Sao10K: Llama 3.1 Euryale 70B v2.2',
    'openrouter/qwen/qwen3.6-35b-a3b': 'Qwen: Qwen3.6 35B A3B',
    'openrouter/qwen/qwen3-32b': 'Qwen: Qwen3 32B',
    'openrouter/qwen/qwen3-vl-32b-instruct': 'Qwen: Qwen3 VL 32B Instruct',
    'openrouter/google/gemma-4-31b-it': 'Google: Gemma 4 31B',
    'openrouter/meta/muse-glimmer-30b': 'Meta: Muse Glimmer 30B',
    'openrouter/qwen/qwen3-30b-a3b': 'Qwen: Qwen3 30B A3B',
    'openrouter/qwen/qwen3-vl-30b-a3b-instruct':
        'Qwen: Qwen3 VL 30B A3B Instruct',
    'openrouter/cohere/command-r-08-2024': 'Cohere: Command R (08-2024)',
    'openrouter/cohere/command-r-plus-08-2024': 'Cohere: Command R+ (08-2024)',
    'openrouter/google/gemma-3-27b-it': 'Google: Gemma 3 27B',
    'openrouter/prism-ml/ternary-bonsai-2-27b': 'PrismML: Ternary Bonsai 2 27B',
    'openrouter/qwen/qwen3.6-27b': 'Qwen: Qwen3.6 27B',
    'openrouter/qwen/qwen3.8-27b': 'Qwen: Qwen3.8 27B',
    'openrouter/unbiased/pareto-26.10-preview': 'Pareto 26.10 Preview',
    'openrouter/google/gemma-4-26b-a4b-it': 'Google: Gemma 4 26B A4B ',
    'openrouter/mistralai/mistral-small-3.1-24b-instruct':
        'Mistral: Mistral Small 3.1 24B',
    'openrouter/mistralai/mistral-small-3.2-24b-instruct':
        'Mistral: Mistral Small 3.2 24B',
    'openrouter/mistralai/mixtral-8x22b-instruct':
        'Mistral: Mixtral 8x22B Instruct',
    'openrouter/openai/gpt-oss-20b': 'OpenAI: gpt-oss-20b',
    'openrouter/openai/gpt-oss-20b:batch': 'OpenAI: gpt-oss-20b (batch)',
    'openrouter/openai/gpt-oss-safeguard-20b': 'OpenAI: gpt-oss-safeguard-20b',
    'openrouter/qwen/qwen3-14b': 'Qwen: Qwen3 14B',
    'openrouter/google/gemma-3-12b-it': 'Google: Gemma 3 12B',
    'openrouter/qwen/qwen3.5-122b-a10b': 'Qwen: Qwen3.5-122B-A10B',
    'openrouter/ibm-granite/granite-4.2-8b': 'IBM: Granite 4.2 8B',
    'openrouter/meta-llama/llama-3.1-8b-instruct':
        'Meta: Llama 3.1 8B Instruct',
    'openrouter/qwen/qwen3-8b': 'Qwen: Qwen3 8B',
    'openrouter/qwen/qwen3-vl-8b-instruct': 'Qwen: Qwen3 VL 8B Instruct',
    'openrouter/qwen/qwen-2.5-7b-instruct': 'Qwen: Qwen2.5 7B Instruct',
    'openrouter/openai/gpt-6.1-sol': 'OpenAI: GPT-6.1 Sol',
    'openrouter/openai/gpt-6-astra': 'OpenAI: GPT-6 Astra',
    'openrouter/openai/gpt-6-astra:batch': 'OpenAI: GPT-6 Astra (batch)',
    'openrouter/openai/gpt-6-luna': 'OpenAI: GPT-6 Luna',
    'openrouter/openai/gpt-6-luna:batch': 'OpenAI: GPT-6 Luna (batch)',
    'openrouter/openai/gpt-6-sol': 'OpenAI: GPT-6 Sol',
    'openrouter/openai/gpt-6-sol:batch': 'OpenAI: GPT-6 Sol (batch)',
    'openrouter/openai/gpt-5.6-luna': 'OpenAI: GPT-5.6 Luna',
    'openrouter/openai/gpt-5.6-luna:batch': 'OpenAI: GPT-5.6 Luna (batch)',
    'openrouter/openai/gpt-5.6-sol': 'OpenAI: GPT-5.6 Sol',
    'openrouter/openai/gpt-5.6-sol:batch': 'OpenAI: GPT-5.6 Sol (batch)',
    'openrouter/openai/gpt-5.6-terra': 'OpenAI: GPT-5.6 Terra',
    'openrouter/openai/gpt-5.6-terra:batch': 'OpenAI: GPT-5.6 Terra (batch)',
    'openrouter/openai/gpt-5.5': 'OpenAI: GPT-5.5',
    'openrouter/openai/gpt-5.5:batch': 'OpenAI: GPT-5.5 (batch)',
    'openrouter/openai/gpt-5.4': 'OpenAI: GPT-5.4',
    'openrouter/openai/gpt-5.4:batch': 'OpenAI: GPT-5.4 (batch)',
    'openrouter/z-ai/glm-5.3': 'Z.ai: GLM 5.3',
    'openrouter/z-ai/glm-5.3:batch': 'Z.ai: GLM 5.3 (batch)',
    'openrouter/z-ai/glm-5.3-flashx': 'Z.ai: GLM 5.3 FlashX',
    'openrouter/z-ai/glm-5.3-prime': 'Z.ai: GLM 5.3 Prime',
    'openrouter/openai/gpt-5.2': 'OpenAI: GPT-5.2',
    'openrouter/openai/gpt-5.2:batch': 'OpenAI: GPT-5.2 (batch)',
    'openrouter/openai/gpt-5.2-chat': 'OpenAI: GPT-5.2 Chat',
    'openrouter/z-ai/glm-5.2': 'Z.ai: GLM 5.2',
    'openrouter/openai/gpt-5.1': 'OpenAI: GPT-5.1',
    'openrouter/openai/gpt-5.1:batch': 'OpenAI: GPT-5.1 (batch)',
    'openrouter/z-ai/glm-5.1': 'Z.ai: GLM 5.1',
    'openrouter/openai/gpt-5': 'OpenAI: GPT-5',
    'openrouter/openai/gpt-5:batch': 'OpenAI: GPT-5 (batch)',
    'openrouter/z-ai/glm-5': 'Z.ai: GLM 5',
    'openrouter/x-ai/grok-4.20': 'SpaceXAI: Grok 4.20',
    'openrouter/x-ai/grok-4.7': 'SpaceXAI: Grok 4.7',
    'openrouter/z-ai/glm-4.7': 'Z.ai: GLM 4.7',
    'openrouter/x-ai/grok-4.6': 'SpaceXAI: Grok 4.6',
    'openrouter/z-ai/glm-4.6': 'Z.ai: GLM 4.6',
    'openrouter/z-ai/glm-4.6v': 'Z.ai: GLM 4.6V',
    'openrouter/x-ai/grok-4.5': 'SpaceXAI: Grok 4.5',
    'openrouter/z-ai/glm-4.5': 'Z.ai: GLM 4.5',
    'openrouter/z-ai/glm-4.5-air': 'Z.ai: GLM 4.5 Air',
    'openrouter/z-ai/glm-4.5v': 'Z.ai: GLM 4.5V',
    'openrouter/x-ai/grok-4.3': 'SpaceXAI: Grok 4.3',
    'openrouter/x-ai/grok-4.3:batch': 'SpaceXAI: Grok 4.3 (batch)',
    'openrouter/openai/gpt-4.1': 'OpenAI: GPT-4.1',
    'openrouter/openai/gpt-4.1:batch': 'OpenAI: GPT-4.1 (batch)',
    'openrouter/meta-llama/llama-4-maverick': 'Meta: Llama 4 Maverick',
    'openrouter/meta-llama/llama-4-scout': 'Meta: Llama 4 Scout',
    'openrouter/openai/gpt-4': 'OpenAI: GPT-4',
    'openrouter/openai/gpt-4o': 'OpenAI: GPT-4o',
    'openrouter/openai/gpt-4o:batch': 'OpenAI: GPT-4o (batch)',
    'openrouter/tencent/hy4-preview': 'Tencent: Hy4 preview',
    'openrouter/qwen/qwen3.7-plus': 'Qwen: Qwen3.7 Plus',
    'openrouter/qwen/qwen3.6-plus': 'Qwen: Qwen3.6 Plus',
    'openrouter/qwen/qwen3.5-35b-a3b': 'Qwen: Qwen3.5-35B-A3B',
    'openrouter/qwen/qwen3.5-27b': 'Qwen: Qwen3.5-27B',
    'openrouter/qwen/qwen3.5-9b': 'Qwen: Qwen3.5-9B',
    'openrouter/aion-labs/aion-3.5': 'AionLabs: Aion 3.5',
    'openrouter/mistralai/mistral-medium-3-5': 'Mistral: Mistral Medium 3.5',
    'openrouter/mistralai/mistral-medium-3-5:batch':
        'Mistral: Mistral Medium 3.5 (batch)',
    'openrouter/nvidia/nemotron-3.5-lightning':
        'NVIDIA: Nemotron 3.5 Lightning',
    'openrouter/deepseek/deepseek-v3.2': 'DeepSeek: DeepSeek V3.2',
    'openrouter/deepseek/deepseek-v3.2-exp': 'DeepSeek: DeepSeek V3.2 Exp',
    'openrouter/deepseek/deepseek-chat-v3.1': 'DeepSeek: DeepSeek V3.1',
    'openrouter/deepseek/deepseek-v3.1-terminus':
        'DeepSeek: DeepSeek V3.1 Terminus',
    'openrouter/mistralai/mistral-medium-3.1': 'Mistral: Mistral Medium 3.1',
    'openrouter/mistralai/mistral-medium-3.1:batch':
        'Mistral: Mistral Medium 3.1 (batch)',
    'openrouter/aion-labs/aion-3.0': 'AionLabs: Aion-3.0',
    'openrouter/deepseek/deepseek-chat': 'DeepSeek: DeepSeek V3',
    'openrouter/minimax/minimax-m3': 'MiniMax: MiniMax M3',
    'openrouter/mistralai/mistral-medium-3': 'Mistral: Mistral Medium 3',
    'openrouter/moonshotai/kimi-k3': 'MoonshotAI: Kimi K3',
    'openrouter/moonshotai/kimi-k3:batch': 'MoonshotAI: Kimi K3 (batch)',
    'openrouter/openai/o3': 'OpenAI: o3',
    'openrouter/openai/o3:batch': 'OpenAI: o3 (batch)',
    'openrouter/tencent/hy3': 'Tencent: Hy3',
    'openrouter/tencent/hy3-preview': 'Tencent: Hy3 preview',
    'openrouter/minimax/minimax-m2.7': 'MiniMax: MiniMax M2.7',
    'openrouter/moonshotai/kimi-k2.6': 'MoonshotAI: Kimi K2.6',
    'openrouter/inception/mercury-2.5': 'Inception: Mercury 2.5',
    'openrouter/minimax/minimax-m2.5': 'MiniMax: MiniMax M2.5',
    'openrouter/moonshotai/kimi-k2.5': 'MoonshotAI: Kimi K2.5',
    'openrouter/xiaomi/mimo-v2.5': 'Xiaomi: MiMo-V2.5',
    'openrouter/minimax/minimax-m2.1': 'MiniMax: MiniMax M2.1',
    'openrouter/poolside/laguna-s-2.1': 'Poolside: Laguna S 2.1',
    'openrouter/poolside/laguna-xs-2.1': 'Poolside: Laguna XS 2.1',
    'openrouter/aion-labs/aion-2.0': 'AionLabs: Aion-2.0',
    'openrouter/inception/mercury-2': 'Inception: Mercury 2',
    'openrouter/meituan/longcat-2.0': 'Meituan: LongCat 2.0',
    'openrouter/minimax/minimax-m2': 'MiniMax: MiniMax M2',
    'openrouter/bytedance-seed/seed-1.6': 'ByteDance Seed: Seed 1.6',
    'openrouter/perceptron/perceptron-mk1.5': 'Perceptron: Perceptron Mk1.5',
    'openrouter/meta/muse-spark-1.3': 'Meta: Muse Spark 1.3',
    'openrouter/meta/muse-spark-1.3-contributor':
        'Meta: Muse Spark 1.3 Contributor',
    'openrouter/meta/muse-spark-1.2': 'Meta: Muse Spark 1.2',
    'openrouter/meta/muse-spark-1.2-contributor':
        'Meta: Muse Spark 1.2 Contributor',
    'openrouter/meta/muse-spark-1.1': 'Meta: Muse Spark 1.1',
    'openrouter/deepseek/deepseek-r1': 'DeepSeek: R1',
    'openrouter/fireworks/ember-1': 'Fireworks: Ember-1',
    'openrouter/minimax/minimax-m1': 'MiniMax: MiniMax M1',
    'openrouter/openai/o1': 'OpenAI: o1',
    'openrouter/x-ai/grok-build-0.1': 'SpaceXAI: Grok Build 0.1',
    'openrouter/auto': 'Auto',
    'openrouter/openrouter/auto': 'Auto Router',
    'openrouter/openrouter/auto-beta': 'Auto Router (Beta)',
    'openrouter/cohere/command-a-plus': 'Cohere: Command A+',
    'openrouter/mistralai/mistral-nemo': 'Mistral: Mistral Nemo',
    'openrouter/mistralai/mistral-saba': 'Mistral: Saba',
    'openrouter/~moonshotai/kimi-latest': 'MoonshotAI: Kimi Latest',
    'openrouter/~openai/gpt-astra-latest': 'OpenAI: GPT Astra Latest',
    'openrouter/openai/gpt-audio': 'OpenAI: GPT Audio',
    'openrouter/openai/gpt-chat-latest': 'OpenAI: GPT Chat Latest',
    'openrouter/~openai/gpt-luna-latest': 'OpenAI: GPT Luna Latest',
    'openrouter/~openai/gpt-sol-latest': 'OpenAI: GPT Sol Latest',
    'openrouter/~openai/gpt-terra-latest': 'OpenAI: GPT Terra Latest',
    'openrouter/openrouter/fusion': 'OpenRouter: Fusion',
    'openrouter/unbiased/pareto': 'Pareto',
    'openrouter/qwen/qwen-plus': 'Qwen: Qwen-Plus',
    'openrouter/rekaai/reka-edge': 'Reka Edge',
    'openrouter/relace/relace-search': 'Relace: Relace Search',
    'openrouter/sakana/sakana-namazu': 'Sakana: Sakana Namazu',
    'openrouter/stealth/space-bunny-alpha': 'Space Bunny Alpha',
    'openrouter/typesafe/jev-router': 'TypeSafe: Jev Router',
    'openrouter/~x-ai/grok-latest': 'xAI: Grok Latest',
    'openrouter/~z-ai/glm-latest': 'Z.ai: GLM Latest',
    'openrouter/thinkingmachines/inkling:free':
        'Thinking Machines: Inkling (free)',
    'openrouter/thinkingmachines/inkling-small:free':
        'Thinking Machines: Inkling Small (free)',
    'openrouter/deepseek/deepseek-v4-flash-0731':
        'DeepSeek: DeepSeek V4 Flash 0731',
    'openrouter/openai/gpt-3.5-turbo-0613':
        'OpenAI: GPT-3.5 Turbo (older v0613)',
    'openrouter/deepseek/deepseek-v4-flash': 'DeepSeek: DeepSeek V4 Flash 0423',
    'openrouter/openai/gpt-3.5-turbo-16k': 'OpenAI: GPT-3.5 Turbo 16k',
    'openrouter/z-ai/glm-5.3-flash': 'Z.ai: GLM 5.3 Flash',
    'openrouter/z-ai/glm-5.3-flash:batch': 'Z.ai: GLM 5.3 Flash (batch)',
    'openrouter/z-ai/glm-5-turbo': 'Z.ai: GLM 5 Turbo',
    'openrouter/z-ai/glm-5v-turbo': 'Z.ai: GLM 5V Turbo',
    'openrouter/z-ai/glm-4.7-flash': 'Z.ai: GLM 4.7 Flash',
    'openrouter/deepseek/deepseek-v4.1-flash': 'DeepSeek: DeepSeek V4.1 Flash',
    'openrouter/deepseek/deepseek-v4.1-flash:batch':
        'DeepSeek: DeepSeek V4.1 Flash (batch)',
    'openrouter/~deepseek/deepseek-v4-flash-latest':
        'DeepSeek: DeepSeek V4 Flash Latest',
    'openrouter/deepseek/deepseek-v4-flash-vision-exp':
        'DeepSeek: DeepSeek V4 Flash Vision Exp',
    'openrouter/openai/gpt-4-turbo': 'OpenAI: GPT-4 Turbo',
    'openrouter/openai/gpt-4-turbo:batch': 'OpenAI: GPT-4 Turbo (batch)',
    'openrouter/google/gemini-3.8-flash': 'Google: Gemini 3.8 Flash',
    'openrouter/google/gemini-3.8-flash:batch':
        'Google: Gemini 3.8 Flash (batch)',
    'openrouter/qwen/qwen3.8-flash': 'Qwen: Qwen3.8 Flash',
    'openrouter/qwen/qwen3.8-omni-flash': 'Qwen: Qwen3.8 Omni Flash',
    'openrouter/google/gemini-3.7-flash': 'Google: Gemini 3.7 Flash',
    'openrouter/google/gemini-3.7-flash:batch':
        'Google: Gemini 3.7 Flash (batch)',
    'openrouter/qwen/qwen3.7-flash': 'Qwen: Qwen3.7 Flash',
    'openrouter/stepfun/step-3.7-flash': 'StepFun: Step 3.7 Flash',
    'openrouter/google/gemini-3.6-flash': 'Google: Gemini 3.6 Flash',
    'openrouter/google/gemini-3.6-flash:batch':
        'Google: Gemini 3.6 Flash (batch)',
    'openrouter/qwen/qwen3.6-flash': 'Qwen: Qwen3.6 Flash',
    'openrouter/google/gemini-3.5-flash': 'Google: Gemini 3.5 Flash',
    'openrouter/google/gemini-3.5-flash:batch':
        'Google: Gemini 3.5 Flash (batch)',
    'openrouter/openai/gpt-3.5-turbo': 'OpenAI: GPT-3.5 Turbo',
    'openrouter/openai/gpt-3.5-turbo:batch': 'OpenAI: GPT-3.5 Turbo (batch)',
    'openrouter/qwen/qwen3.5-flash-02-23': 'Qwen: Qwen3.5-Flash',
    'openrouter/stepfun/step-3.5-flash': 'StepFun: Step 3.5 Flash',
    'openrouter/inclusionai/ling-3.1-flash': 'inclusionAI: Ling 3.1 Flash',
    'openrouter/google/gemini-3-flash-preview':
        'Google: Gemini 3 Flash Preview',
    'openrouter/google/gemini-3-flash-preview:batch':
        'Google: Gemini 3 Flash Preview (batch)',
    'openrouter/inclusionai/ling-3.0-flash': 'inclusionAI: Ling 3.0 Flash',
    'openrouter/inclusionai/ling-3.0-flash-fin':
        'inclusionAI: Ling 3.0 Flash Fin',
    'openrouter/inclusionai/ling-3.0-flash-vl':
        'inclusionAI: Ling 3.0 Flash VL',
    'openrouter/xiaomi/mimo-v2.6-flash': 'Xiaomi: MiMo-V2.6-Flash',
    'openrouter/google/gemini-2.5-flash': 'Google: Gemini 2.5 Flash',
    'openrouter/google/gemini-2.5-flash:batch':
        'Google: Gemini 2.5 Flash (batch)',
    'openrouter/bytedance-seed/seed-2-1-turbo':
        'ByteDance Seed: Seed 2.1 Turbo',
    'openrouter/bytedance-seed/seed-1.6-flash':
        'ByteDance Seed: Seed 1.6 Flash',
    'openrouter/~deepseek/deepseek-flash-latest':
        'DeepSeek: DeepSeek Flash Latest',
    'openrouter/~google/gemini-flash-latest': 'Google: Gemini Flash Latest',
    'openrouter/~z-ai/glm-flash-latest': 'Z.ai: GLM Flash Latest',
    'openrouter/nvidia/nemotron-3-super-120b-a12b:free':
        'NVIDIA: Nemotron 3 Super (free)',
    'openrouter/openai/gpt-4o-mini-2024-07-18':
        'OpenAI: GPT-4o-mini (2024-07-18)',
    'openrouter/nvidia/nemotron-3-nano-30b-a3b':
        'NVIDIA: Nemotron 3 Nano 30B A3B',
    'openrouter/openai/gpt-5.4-mini': 'OpenAI: GPT-5.4 Mini',
    'openrouter/openai/gpt-5.4-mini:batch': 'OpenAI: GPT-5.4 Mini (batch)',
    'openrouter/openai/gpt-5.4-nano': 'OpenAI: GPT-5.4 Nano',
    'openrouter/openai/gpt-5.4-nano:batch': 'OpenAI: GPT-5.4 Nano (batch)',
    'openrouter/openai/gpt-5-mini': 'OpenAI: GPT-5 Mini',
    'openrouter/openai/gpt-5-mini:batch': 'OpenAI: GPT-5 Mini (batch)',
    'openrouter/openai/gpt-5-nano': 'OpenAI: GPT-5 Nano',
    'openrouter/openai/gpt-5-nano:batch': 'OpenAI: GPT-5 Nano (batch)',
    'openrouter/openai/gpt-4.1-mini': 'OpenAI: GPT-4.1 Mini',
    'openrouter/openai/gpt-4.1-mini:batch': 'OpenAI: GPT-4.1 Mini (batch)',
    'openrouter/openai/gpt-4.1-nano': 'OpenAI: GPT-4.1 Nano',
    'openrouter/openai/gpt-4.1-nano:batch': 'OpenAI: GPT-4.1 Nano (batch)',
    'openrouter/openai/gpt-4o-mini': 'OpenAI: GPT-4o-mini',
    'openrouter/openai/gpt-4o-mini:batch': 'OpenAI: GPT-4o-mini (batch)',
    'openrouter/openai/o4-mini': 'OpenAI: o4 Mini',
    'openrouter/openai/o4-mini:batch': 'OpenAI: o4 Mini (batch)',
    'openrouter/openai/o4-mini-high': 'OpenAI: o4 Mini High',
    'openrouter/upstage/solar-mini4': 'Upstage: Solar Mini 4',
    'openrouter/aion-labs/aion-3.5-mini': 'AionLabs: Aion 3.5 Mini',
    'openrouter/aion-labs/aion-3.0-mini': 'AionLabs: Aion-3.0-Mini',
    'openrouter/openai/o3-mini': 'OpenAI: o3 Mini',
    'openrouter/openai/o3-mini:batch': 'OpenAI: o3 Mini (batch)',
    'openrouter/openai/o3-mini-high': 'OpenAI: o3 Mini High',
    'openrouter/amazon/nova-2-lite-v1': 'Amazon: Nova 2 Lite',
    'openrouter/bytedance-seed/seed-2.0-lite': 'ByteDance Seed: Seed-2.0-Lite',
    'openrouter/bytedance-seed/seed-2.0-mini': 'ByteDance Seed: Seed-2.0-Mini',
    'openrouter/amazon/nova-lite-v1': 'Amazon: Nova Lite 1.0',
    'openrouter/amazon/nova-micro-v1': 'Amazon: Nova Micro 1.0',
    'openrouter/cohere/north-mini-code:free': 'Cohere: North Mini Code (free)',
    'openrouter/openai/gpt-audio-mini': 'OpenAI: GPT Audio Mini',
    'openrouter/~openai/gpt-mini-latest': 'OpenAI: GPT Mini Latest',
    'openrouter/google/gemma-4-31b-it:free': 'Google: Gemma 4 31B (free)',
    'openrouter/nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free':
        'NVIDIA: Nemotron 3 Nano Omni (free)',
    'openrouter/qwen/qwen3.8-27b:free': 'Qwen: Qwen3.8 27B (free)',
    'openrouter/google/gemma-4-26b-a4b-it:free':
        'Google: Gemma 4 26B A4B  (free)',
    'openrouter/nvidia/nemotron-3.5-lightning:free':
        'NVIDIA: Nemotron 3.5 Lightning (free)',
    'openrouter/dots-studio/dots-3-note-preview:free':
        'Dots Studio: Dots3-Note Preview (free)',
    'openrouter/liquid/lfm-2.5-2.6b:free': 'LiquidAI: LFM2.5-2.6B (free)',
    'openrouter/poolside/laguna-s-2.1:free': 'Poolside: Laguna S 2.1 (free)',
    'openrouter/poolside/laguna-xs-2.1:free': 'Poolside: Laguna XS 2.1 (free)',
    'openrouter/openrouter/free': 'Free Models Router',
    'openrouter/google/gemini-3.5-flash-lite': 'Google: Gemini 3.5 Flash Lite',
    'openrouter/google/gemini-3.5-flash-lite:batch':
        'Google: Gemini 3.5 Flash Lite (batch)',
    'openrouter/google/gemini-3.1-flash-lite': 'Google: Gemini 3.1 Flash Lite',
    'openrouter/google/gemini-3.1-flash-lite:batch':
        'Google: Gemini 3.1 Flash Lite (batch)',
    'openrouter/google/gemini-3.1-flash-lite-preview':
        'Google: Gemini 3.1 Flash Lite Preview',
    'openrouter/google/gemini-2.5-flash-lite': 'Google: Gemini 2.5 Flash Lite',
    'openrouter/google/gemini-2.5-flash-lite:batch':
        'Google: Gemini 2.5 Flash Lite (batch)',
    'openrouter/inclusionai/ling-3.0-flash-sante:free':
        'inclusionAI: Ling 3.0 Flash Sante (free)',
    'openrouter/apodex/apodex-1.1-mini:free': 'Apodex: Apodex 1.1 Mini (free)',
    'openai/gpt-5.5-pro': 'GPT-5.5 Pro',
    'openai/gpt-5.4-pro': 'GPT-5.4 Pro',
    'openai/gpt-5.2-pro': 'GPT-5.2 Pro',
    'openai/gpt-5-pro': 'GPT-5 Pro',
    'openai/o3-pro': 'o3-pro',
    'openai/o1-pro': 'o1-pro',
    'openai/gpt-5.3-codex': 'GPT-5.3 Codex',
    'openai/gpt-5.3-codex-spark': 'GPT-5.3 Codex Spark',
    'openai/gpt-4o-2024-11-20': 'GPT-4o (2024-11-20)',
    'openai/gpt-4o-2024-08-06': 'GPT-4o (2024-08-06)',
    'openai/gpt-4o-2024-05-13': 'GPT-4o (2024-05-13)',
    'openai/gpt-6.1-sol': 'GPT-6.1 Sol',
    'openai/gpt-6-astra': 'GPT-6 Astra',
    'openai/gpt-6-luna': 'GPT-6 Luna',
    'openai/gpt-6-sol': 'GPT-6 Sol',
    'openai/gpt-5.6-luna': 'GPT-5.6 Luna',
    'openai/gpt-5.6-sol': 'GPT-5.6 Sol',
    'openai/gpt-5.6-terra': 'GPT-5.6 Terra',
    'openai/gpt-5.5': 'GPT-5.5',
    'openai/gpt-5.4': 'GPT-5.4',
    'openai/gpt-5.3-chat-latest': 'GPT-5.3 Chat (latest)',
    'openai/gpt-5.2': 'GPT-5.2',
    'openai/gpt-5.2-chat-latest': 'GPT-5.2 Chat',
    'openai/gpt-5.1': 'GPT-5.1',
    'openai/gpt-5': 'GPT-5',
    'openai/gpt-5-chat-latest': 'GPT-5 Chat Latest',
    'openai/gpt-4.1': 'GPT-4.1',
    'openai/gpt-4': 'GPT-4',
    'openai/gpt-4o': 'GPT-4o',
    'openai/o3': 'o3',
    'openai/gpt-realtime-2.1': 'GPT-Realtime-2.1',
    'openai/o1': 'o1',
    'openai/gpt-daybreak-blue-latest': 'Daybreak Blue',
    'openai/gpt-daybreak-red-latest': 'Daybreak Red',
    'openai/gpt-4-turbo': 'GPT-4 Turbo',
    'openai/gpt-5.4-mini': 'GPT-5.4 mini',
    'openai/gpt-5.4-nano': 'GPT-5.4 nano',
    'openai/gpt-5-mini': 'GPT-5 Mini',
    'openai/gpt-5-nano': 'GPT-5 Nano',
    'openai/gpt-4.1-mini': 'GPT-4.1 mini',
    'openai/gpt-4.1-nano': 'GPT-4.1 nano',
    'openai/gpt-4o-mini': 'GPT-4o mini',
    'openai/o4-mini': 'o4-mini',
    'openai/o3-mini': 'o3-mini',
    'anthropic/claude-fable-5-1': 'Claude Fable 5.1',
    'anthropic/claude-fable-5': 'Claude Fable 5',
    'anthropic/claude-opus-4-5-20251101': 'Claude Opus 4.5',
    'anthropic/claude-opus-5-5': 'Claude Opus 5.5',
    'anthropic/claude-opus-5': 'Claude Opus 5',
    'anthropic/claude-opus-4-8': 'Claude Opus 4.8',
    'anthropic/claude-opus-4-7': 'Claude Opus 4.7',
    'anthropic/claude-opus-4-6': 'Claude Opus 4.6',
    'anthropic/claude-opus-4-5': 'Claude Opus 4.5 (latest)',
    'anthropic/claude-sonnet-4-5-20250929': 'Claude Sonnet 4.5',
    'anthropic/claude-sonnet-5-5': 'Claude Sonnet 5.5',
    'anthropic/claude-sonnet-5': 'Claude Sonnet 5',
    'anthropic/claude-sonnet-4-6': 'Claude Sonnet 4.6',
    'anthropic/claude-sonnet-4-5': 'Claude Sonnet 4.5 (latest)',
    'anthropic/claude-haiku-4-5-20251001': 'Claude Haiku 4.5',
    'anthropic/claude-haiku-4-5': 'Claude Haiku 4.5 (latest)',
    'google/deep-research-max-preview-04-2026':
        'Deep Research Max Preview (Apr-21-2026)',
    'google/gemini-3.1-pro-preview': 'Gemini 3.1 Pro Preview',
    'google/gemini-3.1-pro-preview-customtools':
        'Gemini 3.1 Pro Preview Custom Tools',
    'google/gemini-2.5-pro': 'Gemini 2.5 Pro',
    'google/deep-research-preview-04-2026':
        'Deep Research Preview (Apr-21-2026)',
    'google/gemma-4-31b-it': 'Gemma 4 31B IT',
    'google/gemini-2.5-computer-use-preview-10-2025':
        'Gemini 2.5 Computer Use Preview 10-2025',
    'google/gemma-4-26b-a4b-it': 'Gemma 4 26B A4B IT',
    'google/gemini-3.8-flash': 'Gemini 3.8 Flash',
    'google/gemini-3.7-flash': 'Gemini 3.7 Flash',
    'google/gemini-3.6-flash': 'Gemini 3.6 Flash',
    'google/gemini-3.5-flash': 'Gemini 3.5 Flash',
    'google/gemini-3.1-flash-live-preview': 'Gemini 3.1 Flash Live Preview',
    'google/gemini-3-flash-preview': 'Gemini 3 Flash Preview',
    'google/gemini-2.5-flash': 'Gemini 2.5 Flash',
    'google/gemini-flash-latest': 'Gemini Flash Latest',
    'google/gemini-3.5-flash-lite': 'Gemini 3.5 Flash Lite',
    'google/gemini-3.1-flash-lite': 'Gemini 3.1 Flash Lite',
    'google/gemini-3.1-flash-lite-preview': 'Gemini 3.1 Flash Lite Preview',
    'google/gemini-3.1-flash-lite-image': 'Nano Banana 2 Lite',
    'google/gemini-2.5-flash-lite': 'Gemini 2.5 Flash-Lite',
    'google/gemini-flash-lite-latest': 'Gemini Flash-Lite Latest',
    'xai/grok-4.7': 'Grok 4.7',
    'xai/grok-4.6': 'Grok 4.6',
    'xai/grok-4.5': 'Grok 4.5',
    'xai/grok-4.3': 'Grok 4.3',
    'xiaomi/mimo-v2.6-pro': 'MiMo-V2.6-Pro',
    'xiaomi/mimo-v2.6-pro-ultraspeed': 'MiMo-V2.6-Pro-UltraSpeed',
    'xiaomi/mimo-v2.5-pro': 'MiMo-V2.5-Pro',
    'xiaomi/mimo-v2.5-pro-ultraspeed': 'MiMo-V2.5-Pro-UltraSpeed',
    'xiaomi/mimo-v2.5': 'MiMo-V2.5',
    'xiaomi/mimo-v2.6-flash': 'MiMo-V2.6-Flash',
  },
  'claude': {
    'opus': 'Claude Opus',
    'fable': 'Claude Fable',
    'sonnet': 'Claude Sonnet',
    'haiku': 'Claude Haiku',
    'claude-opus-5-5': 'Claude Opus 5.5',
    'claude-opus-5': 'Claude Opus 5',
    'claude-opus-4-8': 'Claude Opus 4.8',
    'claude-opus-4-7': 'Claude Opus 4.7',
    'claude-opus-4-6': 'Claude Opus 4.6',
    'claude-fable-5-1': 'Claude Fable 5.1',
    'claude-fable-5': 'Claude Fable 5',
    'claude-sonnet-5-5': 'Claude Sonnet 5.5',
    'claude-sonnet-5': 'Claude Sonnet 5',
    'claude-sonnet-4-6': 'Claude Sonnet 4.6',
    'claude-haiku-4-5': 'Claude Haiku 4.5',
  },
  'codex': {
    'gpt-6-astra': 'GPT-6-Astra',
    'gpt-5.6-sol': 'GPT-5.6 Sol',
    'gpt-5.6-terra': 'GPT-5.6 Terra',
    'gpt-5.6-luna': 'GPT-5.6 Luna',
    'gpt-5.5': 'GPT-5.5',
    'gpt-5.4': 'GPT-5.4',
    'gpt-5.3-codex': 'GPT-5.3 Codex',
    'gpt-5.3-codex-spark': 'GPT-5.3 Codex Spark',
    'gpt-5.2-codex': 'GPT-5.2 Codex',
    'gpt-5.2': 'GPT-5.2',
    'gpt-5.1-codex-max': 'GPT-5.1 Codex Max',
    'gpt-5.1-codex': 'GPT-5.1 Codex',
    'gpt-5-codex': 'GPT-5 Codex',
    'gpt-5': 'GPT-5',
  },
  'grok': {
    'grok-4.5': 'Grok 4.5',
    'grok-4.6': 'Grok 4.6',
    'grok-composer-2.5-fast': 'Composer 2.5',
  },
  'antigravity': {'default': 'AGY configured default'},
  'copilot': {
    'gpt-5.4': 'GPT-5.4',
    'gpt-5.2': 'GPT-5.2',
    'claude-4-sonnet': 'Claude 4 Sonnet',
    'claude-4.5-sonnet': 'Claude 4.5 Sonnet',
  },
  'cursor': {
    'composer-2-fast': 'Composer 2 Fast',
    'composer-2': 'Composer 2',
    'auto': 'Auto',
  },
  'gemini': {
    'default': 'Configured Default / Auto',
    'gemini-3.1-pro-preview': 'Gemini 3.1 Pro (Preview)',
    'gemini-3-flash-preview': 'Gemini 3 Flash (Preview)',
    'gemini-2.5-pro': 'Gemini 2.5 Pro',
    'gemini-2.5-flash': 'Gemini 2.5 Flash',
  },
  'opencode': {
    'default': 'Configured Default / Auto',
    'deepseek/deepseek-v4-pro': 'DeepSeek V4 Pro · DeepSeek',
    'openrouter/anthropic/claude-opus-4.5':
        'Claude Opus 4.5 · Anthropic via OpenRouter',
    'fusecode/opus[1m]': 'Opus 1M · FuseCode',
  },
  'pi': {'default': 'Configured Default / Auto'},
  'kimi': {'default': 'Configured Default'},
  'kimi-sdk': {'kimi-code/kimi-for-coding': 'Kimi for Coding (default)'},
};
const sourceAgentActivities = <String>{
  'online',
  'thinking',
  'working',
  'error',
  'offline',
};
const sourceAgentDetailKinds = <String>{
  'none',
  'message_received',
  'freshness_hold',
  'starting',
  'runtime_starting',
  'idle',
  'running_command',
  'checking_messages',
  'compacting_context',
  'compaction_finished',
  'compaction_stale',
  'reviewing_changes',
  'review_finished',
  'review_stale',
  'runtime_reconnecting',
  'runtime_error',
  'runtime_crashed',
  'runtime_unavailable',
  'runtime_stalled',
  'delivery_unconsumed',
  'wake_crash_loop_blocked',
  'terminal_failure_paused',
  'stalled_recovery',
  'stopped',
  'ready',
  'runtime_interrupted',
  'machine_disconnected',
  'computer_started',
  'computer_restarted',
  'computer_upgraded',
  'computer_operation_failed',
  'daemon_activity',
  'external_activity',
  'synthetic_repair',
  'slock_action',
  'system_message',
  'runtime_progress',
  'provider_request_status',
  'model_request_started',
  'model_response_started',
  'tool_started',
  'tool_end',
  'thinking_started',
  'thinking_end',
  'subagent_activity',
  'other',
};
