#!/usr/bin/env python3
"""Generate packages/raft_ui/lib/src/brand_marks.g.dart from the Web brand SVGs.

Sources (raft-source packages/web): public/brand/raft-icon.svg, public/brand/raft-logo.svg,
src/assets/icons/provider_{google,github,apple}.svg. Only <path d fill> elements are used
(the files contain nothing else).
"""
import os, pathlib, re

root = pathlib.Path(__file__).resolve().parents[2]
web = pathlib.Path(os.environ.get(
    'PARITY_RAFT_SOURCE',
    '/home/kevinzhow/.slock/agents/9a92b742-8942-488c-8635-67d224ec54ab/work/raft-source')) / 'packages/web'
marks = [
    ('raftIcon', web / 'public/brand/raft-icon.svg'),
    ('raftLogo', web / 'public/brand/raft-logo.svg'),
    ('providerGoogle', web / 'src/assets/icons/provider_google.svg'),
    ('providerGithub', web / 'src/assets/icons/provider_github.svg'),
    ('providerApple', web / 'src/assets/icons/provider_apple.svg'),
]
out = ['// GENERATED by tool/gen-brand/gen.py from the Web brand/provider SVGs.',
       '// Do not edit by hand.', "part of 'brand.dart';", '']
for name, path in marks:
    s = path.read_text()
    vb = re.search(r'viewBox=["\']([^"\']+)["\']', s).group(1).split()
    out.append(f'// {path.relative_to(web)}')
    out.append(f'const RaftBrandSvg _{name} = RaftBrandSvg(')
    out.append(f'  width: {vb[2]},')
    out.append(f'  height: {vb[3]},')
    out.append('  paths: [')
    for m in re.finditer(r'<path\b([^>]*)/?>', s):
        attrs = m.group(1)
        d = re.search(r'\bd=["\']([^"\']*)["\']', attrs).group(1)
        fill = re.search(r'\bfill=["\']([^"\']*)["\']', attrs).group(1)
        fill = {'black': '#000000'}.get(fill, fill)
        out.append(f"    (0xFF{fill[1:].upper()}, '{d}'),")
    out.append('  ],')
    out.append(');')
    out.append('')
(root / 'packages/raft_ui/lib/src/brand_marks.g.dart').write_text('\n'.join(out))
print('wrote brand_marks.g.dart')
