// Geometry from lucide-react 0.575.0 (ISC), pinned Web dependency.
// See packages/raft_ui/LICENSE-LUCIDE. Generated by design-parity/components/generate-icons.py.
import 'package:flutter/material.dart';

part 'reaction_sprite.dart';

enum RaftGlyph {
  wifiOff,
  hardDrive,
  home,
  bell,
  circleCheck,
  share2,
  send,
  pencil,
  paperclip,
  imagePlus,
  plus,
  arrowUp,
  arrowLeft,
  chevronRight,
  chevronLeft,
  chevronDown,
  check,
  x,
  ellipsis,
  messageSquare,
  circle,
  reply,
  file,
  fileText,
  trash2,
  download,
  copy,
  eye,
  eyeOff,
  search,
  settings,
  user,
  users,
  bot,
  monitor,
  bookmark,
  bookmarkFilled,
  activity,
  squareCheck,
  chevronsUpDown,
  calendar,
  calendarRange,
  clock3,
  star,
  arrowDownUp,
  info,
  triangleAlert,
  logOut,
  menu,
  externalLink,
  refreshCw,
  atSign,
  hash,
  gitBranch,
  lock,
  globe,
  slidersHorizontal,
  sun,
  moon,
  palette,
  terminal,
  code,
  checkCheck,
  image,
  maximize,
  minimize,
  zoomIn,
  zoomOut,
  play,
  pause,
  volumeX,
  volume2,
  rotateCw,
  link,
  list,
  columns2,
  circleUserRound,
  laptop,
  loaderCircle,
  ban,
  checkSquare,
  userCircle2,
  columns,
  moreHorizontal,
  code2,
  maximize2,
  forward,
  chevronUp,
}

/// Exact 24-unit Lucide geometry, with rounded 2-unit strokes.
class RaftIcon extends StatelessWidget {
  const RaftIcon(
    this.glyph, {
    super.key,
    this.size = 18,
    this.color,
    this.strokeWidth = 2,
    this.semanticLabel,
  });
  final RaftGlyph glyph;
  final double size, strokeWidth;
  final Color? color;
  final String? semanticLabel;
  @override
  Widget build(BuildContext context) => Semantics(
    label: semanticLabel,
    excludeSemantics: true,
    child: Center(
      widthFactor: 1,
      heightFactor: 1,
      child: SizedBox.square(
        dimension: size,
        child: CustomPaint(
          painter: _LucidePainter(
            glyph,
            color ??
                IconTheme.of(context).color ??
                Theme.of(context).colorScheme.onSurface,
            strokeWidth,
          ),
        ),
      ),
    ),
  );
}

class _LucidePainter extends CustomPainter {
  const _LucidePainter(this.glyph, this.color, this.strokeWidth);
  final RaftGlyph glyph;
  final Color color;
  final double strokeWidth;
  @override
  void paint(Canvas canvas, Size size) {
    canvas.scale(size.width / 24, size.height / 24);
    final paint = Paint()
      ..color = color
      ..style = PaintingStyle.stroke
      ..strokeWidth = strokeWidth
      ..strokeCap = StrokeCap.round
      ..strokeJoin = StrokeJoin.round;
    for (final node in _nodes[_canonical(glyph)]!) {
      final a = node.$2;
      double n(String k, [double fallback = 0]) =>
          double.tryParse(a[k]?.toString() ?? '') ?? fallback;
      switch (node.$1) {
        case 'path':
          final path = _svgPath(a['d']! as String);
          if (glyph == RaftGlyph.bookmarkFilled) {
            canvas.drawPath(path, Paint()..color = color);
          }
          canvas.drawPath(path, paint);
        case 'circle':
          canvas.drawCircle(Offset(n('cx'), n('cy')), n('r'), paint);
        case 'ellipse':
          canvas.drawOval(
            Rect.fromCenter(
              center: Offset(n('cx'), n('cy')),
              width: n('rx') * 2,
              height: n('ry') * 2,
            ),
            paint,
          );
        case 'line':
          canvas.drawLine(
            Offset(n('x1'), n('y1')),
            Offset(n('x2'), n('y2')),
            paint,
          );
        case 'rect':
          canvas.drawRRect(
            RRect.fromRectAndRadius(
              Rect.fromLTWH(n('x'), n('y'), n('width'), n('height')),
              Radius.circular(n('rx')),
            ),
            paint,
          );
        case 'polyline':
        case 'polygon':
          final points = RegExp(r'[-+]?(?:\d*\.\d+|\d+)(?:[eE][-+]?\d+)?')
              .allMatches(a['points']! as String)
              .map((m) => double.parse(m[0]!))
              .toList();
          final path = Path()..moveTo(points[0], points[1]);
          for (var i = 2; i < points.length; i += 2) {
            path.lineTo(points[i], points[i + 1]);
          }
          if (node.$1 == 'polygon') path.close();
          canvas.drawPath(path, paint);
      }
    }
  }

  @override
  bool shouldRepaint(_LucidePainter old) =>
      old.glyph != glyph ||
      old.color != color ||
      old.strokeWidth != strokeWidth;
}

RaftGlyph _canonical(RaftGlyph glyph) => switch (glyph) {
  RaftGlyph.checkSquare => RaftGlyph.squareCheck,
  RaftGlyph.userCircle2 => RaftGlyph.circleUserRound,
  RaftGlyph.columns => RaftGlyph.columns2,
  RaftGlyph.moreHorizontal => RaftGlyph.ellipsis,
  RaftGlyph.bookmarkFilled => RaftGlyph.bookmark,
  _ => glyph,
};

Path _svgPath(String source) {
  final tokens = RegExp(r'[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+)(?:[eE][-+]?\d+)?')
      .allMatches(source)
      .map((m) => m[0]!)
      .toList();
  final path = Path();
  var i = 0;
  var command = '', previous = '';
  var current = Offset.zero, start = Offset.zero;
  Offset? cubic, quadratic;
  double number() => double.parse(tokens[i++]);
  while (i < tokens.length) {
    if (RegExp(r'^[a-zA-Z]$').hasMatch(tokens[i])) command = tokens[i++];
    final relative = command == command.toLowerCase();
    final op = command.toUpperCase();
    Offset point() {
      final p = Offset(number(), number());
      return relative ? current + p : p;
    }

    Offset? nextCubic, nextQuadratic;
    switch (op) {
      case 'M':
        current = point();
        path.moveTo(current.dx, current.dy);
        start = current;
        command = relative ? 'l' : 'L';
      case 'L':
        current = point();
        path.lineTo(current.dx, current.dy);
      case 'H':
        current = Offset(number() + (relative ? current.dx : 0), current.dy);
        path.lineTo(current.dx, current.dy);
      case 'V':
        current = Offset(current.dx, number() + (relative ? current.dy : 0));
        path.lineTo(current.dx, current.dy);
      case 'C':
        final a = point(), b = point(), end = point();
        path.cubicTo(a.dx, a.dy, b.dx, b.dy, end.dx, end.dy);
        current = end;
        nextCubic = b;
      case 'S':
        final a = {'C', 'S'}.contains(previous) && cubic != null
            ? current * 2 - cubic
            : current;
        final b = point(), end = point();
        path.cubicTo(a.dx, a.dy, b.dx, b.dy, end.dx, end.dy);
        current = end;
        nextCubic = b;
      case 'Q':
        final a = point(), end = point();
        path.quadraticBezierTo(a.dx, a.dy, end.dx, end.dy);
        current = end;
        nextQuadratic = a;
      case 'T':
        final a = {'Q', 'T'}.contains(previous) && quadratic != null
            ? current * 2 - quadratic
            : current;
        final end = point();
        path.quadraticBezierTo(a.dx, a.dy, end.dx, end.dy);
        current = end;
        nextQuadratic = a;
      case 'A':
        final rx = number(), ry = number(), rotation = number();
        final large = number() != 0, clockwise = number() != 0;
        final end = point();
        path.arcToPoint(
          end,
          radius: Radius.elliptical(rx, ry),
          rotation: rotation,
          largeArc: large,
          clockwise: clockwise,
        );
        current = end;
      case 'Z':
        path.close();
        current = start;
        command = '';
      default:
        throw FormatException('Unsupported Lucide path command $command');
    }
    previous = op;
    cubic = nextCubic;
    quadratic = nextQuadratic;
  }
  return path;
}

const _nodes = <RaftGlyph, List<(String, Map<String, Object>)>>{
  RaftGlyph.wifiOff: [
    ("path", {"d": "M12 20h.01"}),
    ("path", {"d": "M8.5 16.429a5 5 0 0 1 7 0"}),
    ("path", {"d": "M5 12.859a10 10 0 0 1 5.17-2.69"}),
    ("path", {"d": "M19 12.859a10 10 0 0 0-2.007-1.523"}),
    ("path", {"d": "M2 8.82a15 15 0 0 1 4.177-2.643"}),
    ("path", {"d": "M22 8.82a15 15 0 0 0-11.288-3.764"}),
    ("path", {"d": "m2 2 20 20"}),
  ],
  RaftGlyph.hardDrive: [
    ("path", {"d": "M10 16h.01"}),
    (
      "path",
      {
        "d": "M2.212 11.577a2 2 0 0 0-.212.896V18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2v-5.527a2 2 0 0 0-.212-.896L18.55 5.11A2 2 0 0 0 16.76 4H7.24a2 2 0 0 0-1.79 1.11z",
      },
    ),
    ("path", {"d": "M21.946 12.013H2.054"}),
    ("path", {"d": "M6 16h.01"}),
  ],
  RaftGlyph.forward: [
    ("path", {"d": "m15 17 5-5-5-5"}),
    ("path", {"d": "M4 18v-2a4 4 0 0 1 4-4h12"}),
  ],
  RaftGlyph.chevronUp: [
    ("path", {"d": "m18 15-6-6-6 6"}),
  ],

  RaftGlyph.code2: [
    ("path", {"d": "m18 16 4-4-4-4"}),
    ("path", {"d": "m6 8-4 4 4 4"}),
    ("path", {"d": "m14.5 4-5 16"}),
  ],
  RaftGlyph.maximize2: [
    ("path", {"d": "M15 3h6v6"}),
    ("path", {"d": "m21 3-7 7"}),
    ("path", {"d": "m3 21 7-7"}),
    ("path", {"d": "M9 21H3v-6"}),
  ],

  RaftGlyph.circleCheck: [
    ("circle", {"cx": "12", "cy": "12", "r": "10"}),
    ("path", {"d": "m9 12 2 2 4-4"}),
  ],

  RaftGlyph.share2: [
    ("circle", {"cx": "18", "cy": "5", "r": "3"}),
    ("circle", {"cx": "6", "cy": "12", "r": "3"}),
    ("circle", {"cx": "18", "cy": "19", "r": "3"}),
    ("line", {"x1": "8.59", "x2": "15.42", "y1": "13.51", "y2": "17.49"}),
    ("line", {"x1": "15.41", "x2": "8.59", "y1": "6.51", "y2": "10.49"}),
  ],

  RaftGlyph.send: [
    (
      "path",
      {
        "d": "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z",
      },
    ),
    ("path", {"d": "m21.854 2.147-10.94 10.939"}),
  ],
  // Pinned lucide-react pencil.js, source inline-draft indicator.
  RaftGlyph.pencil: [
    (
      'path',
      {
        'd': 'M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z',
      },
    ),
    ('path', {'d': 'm15 5 4 4'}),
  ],
  RaftGlyph.paperclip: [
    (
      "path",
      {
        "d": "m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551",
      },
    ),
  ],
  RaftGlyph.imagePlus: [
    ("path", {"d": "M16 5h6"}),
    ("path", {"d": "M19 2v6"}),
    (
      "path",
      {"d": "M21 11.5V19a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7.5"},
    ),
    ("path", {"d": "m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}),
    ("circle", {"cx": "9", "cy": "9", "r": "2"}),
  ],
  RaftGlyph.plus: [
    ("path", {"d": "M5 12h14"}),
    ("path", {"d": "M12 5v14"}),
  ],
  RaftGlyph.arrowUp: [
    ("path", {"d": "m5 12 7-7 7 7"}),
    ("path", {"d": "M12 19V5"}),
  ],
  RaftGlyph.arrowLeft: [
    ("path", {"d": "m12 19-7-7 7-7"}),
    ("path", {"d": "M19 12H5"}),
  ],
  RaftGlyph.chevronRight: [
    ("path", {"d": "m9 18 6-6-6-6"}),
  ],
  RaftGlyph.chevronLeft: [
    ("path", {"d": "m15 18-6-6 6-6"}),
  ],
  RaftGlyph.chevronDown: [
    ("path", {"d": "m6 9 6 6 6-6"}),
  ],
  RaftGlyph.check: [
    ("path", {"d": "M20 6 9 17l-5-5"}),
  ],
  RaftGlyph.x: [
    ("path", {"d": "M18 6 6 18"}),
    ("path", {"d": "m6 6 12 12"}),
  ],
  RaftGlyph.ellipsis: [
    ("circle", {"cx": "12", "cy": "12", "r": "1"}),
    ("circle", {"cx": "19", "cy": "12", "r": "1"}),
    ("circle", {"cx": "5", "cy": "12", "r": "1"}),
  ],
  RaftGlyph.messageSquare: [
    (
      "path",
      {
        "d": "M22 17a2 2 0 0 1-2 2H6.828a2 2 0 0 0-1.414.586l-2.202 2.202A.71.71 0 0 1 2 21.286V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2z",
      },
    ),
  ],
  RaftGlyph.circle: [
    ("circle", {"cx": "12", "cy": "12", "r": "10"}),
  ],
  RaftGlyph.reply: [
    ("path", {"d": "M20 18v-2a4 4 0 0 0-4-4H4"}),
    ("path", {"d": "m9 17-5-5 5-5"}),
  ],
  RaftGlyph.file: [
    (
      "path",
      {
        "d": "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
      },
    ),
    ("path", {"d": "M14 2v5a1 1 0 0 0 1 1h5"}),
  ],
  RaftGlyph.fileText: [
    (
      "path",
      {
        "d": "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
      },
    ),
    ("path", {"d": "M14 2v5a1 1 0 0 0 1 1h5"}),
    ("path", {"d": "M10 9H8"}),
    ("path", {"d": "M16 13H8"}),
    ("path", {"d": "M16 17H8"}),
  ],
  RaftGlyph.trash2: [
    ("path", {"d": "M10 11v6"}),
    ("path", {"d": "M14 11v6"}),
    ("path", {"d": "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6"}),
    ("path", {"d": "M3 6h18"}),
    ("path", {"d": "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"}),
  ],
  RaftGlyph.download: [
    ("path", {"d": "M12 15V3"}),
    ("path", {"d": "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"}),
    ("path", {"d": "m7 10 5 5 5-5"}),
  ],
  RaftGlyph.copy: [
    (
      "rect",
      {"width": "14", "height": "14", "x": "8", "y": "8", "rx": "2", "ry": "2"},
    ),
    ("path", {"d": "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2"}),
  ],
  RaftGlyph.eye: [
    (
      "path",
      {
        "d": "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      },
    ),
    ("circle", {"cx": "12", "cy": "12", "r": "3"}),
  ],
  RaftGlyph.eyeOff: [
    (
      "path",
      {
        "d": "M10.733 5.076a10.744 10.744 0 0 1 11.205 6.575 1 1 0 0 1 0 .696 10.747 10.747 0 0 1-1.444 2.49",
      },
    ),
    ("path", {"d": "M14.084 14.158a3 3 0 0 1-4.242-4.242"}),
    (
      "path",
      {
        "d": "M17.479 17.499a10.75 10.75 0 0 1-15.417-5.151 1 1 0 0 1 0-.696 10.75 10.75 0 0 1 4.446-5.143",
      },
    ),
    ("path", {"d": "m2 2 20 20"}),
  ],
  RaftGlyph.search: [
    ("path", {"d": "m21 21-4.34-4.34"}),
    ("circle", {"cx": "11", "cy": "11", "r": "8"}),
  ],
  RaftGlyph.settings: [
    (
      "path",
      {
        "d": "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915",
      },
    ),
    ("circle", {"cx": "12", "cy": "12", "r": "3"}),
  ],
  RaftGlyph.user: [
    ("path", {"d": "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2"}),
    ("circle", {"cx": "12", "cy": "7", "r": "4"}),
  ],
  RaftGlyph.users: [
    ("path", {"d": "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"}),
    ("path", {"d": "M16 3.128a4 4 0 0 1 0 7.744"}),
    ("path", {"d": "M22 21v-2a4 4 0 0 0-3-3.87"}),
    ("circle", {"cx": "9", "cy": "7", "r": "4"}),
  ],
  RaftGlyph.bot: [
    ("path", {"d": "M12 8V4H8"}),
    ("rect", {"width": "16", "height": "12", "x": "4", "y": "8", "rx": "2"}),
    ("path", {"d": "M2 14h2"}),
    ("path", {"d": "M20 14h2"}),
    ("path", {"d": "M15 13v2"}),
    ("path", {"d": "M9 13v2"}),
  ],
  RaftGlyph.monitor: [
    ("rect", {"width": "20", "height": "14", "x": "2", "y": "3", "rx": "2"}),
    ("line", {"x1": "8", "x2": "16", "y1": "21", "y2": "21"}),
    ("line", {"x1": "12", "x2": "12", "y1": "17", "y2": "21"}),
  ],
  RaftGlyph.bookmark: [
    (
      "path",
      {
        "d": "M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z",
      },
    ),
  ],
  RaftGlyph.activity: [
    (
      "path",
      {
        "d": "M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2",
      },
    ),
  ],
  RaftGlyph.squareCheck: [
    ("rect", {"width": "18", "height": "18", "x": "3", "y": "3", "rx": "2"}),
    ("path", {"d": "m9 12 2 2 4-4"}),
  ],
  RaftGlyph.chevronsUpDown: [
    ("path", {"d": "m7 15 5 5 5-5"}),
    ("path", {"d": "m7 9 5-5 5 5"}),
  ],
  // lucide-react 0.575.0 calendar-range / arrow-down-up originals.
  RaftGlyph.clock3: [
    ('circle', {'cx': '12', 'cy': '12', 'r': '10'}),
    ('path', {'d': 'M12 6v6h4'}),
  ],
  RaftGlyph.star: [
    (
      'path',
      {
        'd': 'M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z',
      },
    ),
  ],
  // Lucide Home is the House alias in the pinned0.575.0 build.
  RaftGlyph.bell: [
    ('path', {'d': 'M10.268 21a2 2 0 0 0 3.464 0'}),
    (
      'path',
      {
        'd': 'M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326',
      },
    ),
  ],
  RaftGlyph.home: [
    ('path', {'d': 'M15 21v-8a1 1 0 0 0-1-1h-4a1 1 0 0 0-1 1v8'}),
    (
      'path',
      {
        'd': 'M3 10a2 2 0 0 1 .709-1.528l7-6a2 2 0 0 1 2.582 0l7 6A2 2 0 0 1 21 10v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z',
      },
    ),
  ],
  RaftGlyph.calendarRange: [
    ('rect', {'width': '18', 'height': '18', 'x': '3', 'y': '4', 'rx': '2'}),
    ('path', {'d': 'M16 2v4'}),
    ('path', {'d': 'M3 10h18'}),
    ('path', {'d': 'M8 2v4'}),
    ('path', {'d': 'M17 14h-6'}),
    ('path', {'d': 'M13 18H7'}),
    ('path', {'d': 'M7 14h.01'}),
    ('path', {'d': 'M17 18h.01'}),
  ],
  RaftGlyph.arrowDownUp: [
    ('path', {'d': 'm3 16 4 4 4-4'}),
    ('path', {'d': 'M7 20V4'}),
    ('path', {'d': 'm21 8-4-4-4 4'}),
    ('path', {'d': 'M17 4v16'}),
  ],
  RaftGlyph.calendar: [
    ("path", {"d": "M8 2v4"}),
    ("path", {"d": "M16 2v4"}),
    ("rect", {"width": "18", "height": "18", "x": "3", "y": "4", "rx": "2"}),
    ("path", {"d": "M3 10h18"}),
  ],
  RaftGlyph.info: [
    ("circle", {"cx": "12", "cy": "12", "r": "10"}),
    ("path", {"d": "M12 16v-4"}),
    ("path", {"d": "M12 8h.01"}),
  ],
  RaftGlyph.triangleAlert: [
    (
      "path",
      {
        "d": "m21.73 18-8-14a2 2 0 0 0-3.48 0l-8 14A2 2 0 0 0 4 21h16a2 2 0 0 0 1.73-3",
      },
    ),
    ("path", {"d": "M12 9v4"}),
    ("path", {"d": "M12 17h.01"}),
  ],
  RaftGlyph.logOut: [
    ("path", {"d": "m16 17 5-5-5-5"}),
    ("path", {"d": "M21 12H9"}),
    ("path", {"d": "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"}),
  ],
  RaftGlyph.menu: [
    ("path", {"d": "M4 5h16"}),
    ("path", {"d": "M4 12h16"}),
    ("path", {"d": "M4 19h16"}),
  ],
  RaftGlyph.externalLink: [
    ("path", {"d": "M15 3h6v6"}),
    ("path", {"d": "M10 14 21 3"}),
    ("path", {"d": "M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"}),
  ],
  RaftGlyph.refreshCw: [
    ("path", {"d": "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8"}),
    ("path", {"d": "M21 3v5h-5"}),
    ("path", {"d": "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16"}),
    ("path", {"d": "M8 16H3v5"}),
  ],
  RaftGlyph.atSign: [
    ("circle", {"cx": "12", "cy": "12", "r": "4"}),
    ("path", {"d": "M16 8v5a3 3 0 0 0 6 0v-1a10 10 0 1 0-4 8"}),
  ],
  RaftGlyph.gitBranch: [
    ("path", {"d": "M15 6a9 9 0 0 0-9 9V3"}),
    ("circle", {"cx": "18", "cy": "6", "r": "3"}),
    ("circle", {"cx": "6", "cy": "18", "r": "3"}),
  ],
  RaftGlyph.hash: [
    ("line", {"x1": "4", "x2": "20", "y1": "9", "y2": "9"}),
    ("line", {"x1": "4", "x2": "20", "y1": "15", "y2": "15"}),
    ("line", {"x1": "10", "x2": "8", "y1": "3", "y2": "21"}),
    ("line", {"x1": "16", "x2": "14", "y1": "3", "y2": "21"}),
  ],
  RaftGlyph.lock: [
    (
      "rect",
      {
        "width": "18",
        "height": "11",
        "x": "3",
        "y": "11",
        "rx": "2",
        "ry": "2",
      },
    ),
    ("path", {"d": "M7 11V7a5 5 0 0 1 10 0v4"}),
  ],
  RaftGlyph.globe: [
    ("circle", {"cx": "12", "cy": "12", "r": "10"}),
    ("path", {"d": "M12 2a14.5 14.5 0 0 0 0 20 14.5 14.5 0 0 0 0-20"}),
    ("path", {"d": "M2 12h20"}),
  ],
  RaftGlyph.slidersHorizontal: [
    ("path", {"d": "M10 5H3"}),
    ("path", {"d": "M12 19H3"}),
    ("path", {"d": "M14 3v4"}),
    ("path", {"d": "M16 17v4"}),
    ("path", {"d": "M21 12h-9"}),
    ("path", {"d": "M21 19h-5"}),
    ("path", {"d": "M21 5h-7"}),
    ("path", {"d": "M8 10v4"}),
    ("path", {"d": "M8 12H3"}),
  ],
  RaftGlyph.sun: [
    ("circle", {"cx": "12", "cy": "12", "r": "4"}),
    ("path", {"d": "M12 2v2"}),
    ("path", {"d": "M12 20v2"}),
    ("path", {"d": "m4.93 4.93 1.41 1.41"}),
    ("path", {"d": "m17.66 17.66 1.41 1.41"}),
    ("path", {"d": "M2 12h2"}),
    ("path", {"d": "M20 12h2"}),
    ("path", {"d": "m6.34 17.66-1.41 1.41"}),
    ("path", {"d": "m19.07 4.93-1.41 1.41"}),
  ],
  RaftGlyph.moon: [
    (
      "path",
      {
        "d": "M20.985 12.486a9 9 0 1 1-9.473-9.472c.405-.022.617.46.402.803a6 6 0 0 0 8.268 8.268c.344-.215.825-.004.803.401",
      },
    ),
  ],
  RaftGlyph.palette: [
    (
      "path",
      {
        "d": "M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z",
      },
    ),
    ("circle", {"cx": "13.5", "cy": "6.5", "r": ".5", "fill": "currentColor"}),
    ("circle", {"cx": "17.5", "cy": "10.5", "r": ".5", "fill": "currentColor"}),
    ("circle", {"cx": "6.5", "cy": "12.5", "r": ".5", "fill": "currentColor"}),
    ("circle", {"cx": "8.5", "cy": "7.5", "r": ".5", "fill": "currentColor"}),
  ],
  RaftGlyph.terminal: [
    ("path", {"d": "M12 19h8"}),
    ("path", {"d": "m4 17 6-6-6-6"}),
  ],
  RaftGlyph.code: [
    ("path", {"d": "m16 18 6-6-6-6"}),
    ("path", {"d": "m8 6-6 6 6 6"}),
  ],
  RaftGlyph.checkCheck: [
    ("path", {"d": "M18 6 7 17l-5-5"}),
    ("path", {"d": "m22 10-7.5 7.5L13 16"}),
  ],
  RaftGlyph.image: [
    (
      "rect",
      {"width": "18", "height": "18", "x": "3", "y": "3", "rx": "2", "ry": "2"},
    ),
    ("circle", {"cx": "9", "cy": "9", "r": "2"}),
    ("path", {"d": "m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21"}),
  ],
  RaftGlyph.maximize: [
    ("path", {"d": "M8 3H5a2 2 0 0 0-2 2v3"}),
    ("path", {"d": "M21 8V5a2 2 0 0 0-2-2h-3"}),
    ("path", {"d": "M3 16v3a2 2 0 0 0 2 2h3"}),
    ("path", {"d": "M16 21h3a2 2 0 0 0 2-2v-3"}),
  ],
  RaftGlyph.minimize: [
    ("path", {"d": "M8 3v3a2 2 0 0 1-2 2H3"}),
    ("path", {"d": "M21 8h-3a2 2 0 0 1-2-2V3"}),
    ("path", {"d": "M3 16h3a2 2 0 0 1 2 2v3"}),
    ("path", {"d": "M16 21v-3a2 2 0 0 1 2-2h3"}),
  ],
  RaftGlyph.zoomIn: [
    ("circle", {"cx": "11", "cy": "11", "r": "8"}),
    ("line", {"x1": "21", "x2": "16.65", "y1": "21", "y2": "16.65"}),
    ("line", {"x1": "11", "x2": "11", "y1": "8", "y2": "14"}),
    ("line", {"x1": "8", "x2": "14", "y1": "11", "y2": "11"}),
  ],
  RaftGlyph.zoomOut: [
    ("circle", {"cx": "11", "cy": "11", "r": "8"}),
    ("line", {"x1": "21", "x2": "16.65", "y1": "21", "y2": "16.65"}),
    ("line", {"x1": "8", "x2": "14", "y1": "11", "y2": "11"}),
  ],
  RaftGlyph.play: [
    (
      "path",
      {
        "d": "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z",
      },
    ),
  ],
  RaftGlyph.pause: [
    ("rect", {"x": "14", "y": "3", "width": "5", "height": "18", "rx": "1"}),
    ("rect", {"x": "5", "y": "3", "width": "5", "height": "18", "rx": "1"}),
  ],
  RaftGlyph.volumeX: [
    (
      "path",
      {
        "d": "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z",
      },
    ),
    ("line", {"x1": "22", "x2": "16", "y1": "9", "y2": "15"}),
    ("line", {"x1": "16", "x2": "22", "y1": "9", "y2": "15"}),
  ],
  RaftGlyph.volume2: [
    (
      "path",
      {
        "d": "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z",
      },
    ),
    ("path", {"d": "M16 9a5 5 0 0 1 0 6"}),
    ("path", {"d": "M19.364 18.364a9 9 0 0 0 0-12.728"}),
  ],
  RaftGlyph.rotateCw: [
    ("path", {"d": "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8"}),
    ("path", {"d": "M21 3v5h-5"}),
  ],
  RaftGlyph.link: [
    (
      "path",
      {"d": "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"},
    ),
    (
      "path",
      {"d": "M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"},
    ),
  ],
  RaftGlyph.list: [
    ("path", {"d": "M3 5h.01"}),
    ("path", {"d": "M3 12h.01"}),
    ("path", {"d": "M3 19h.01"}),
    ("path", {"d": "M8 5h13"}),
    ("path", {"d": "M8 12h13"}),
    ("path", {"d": "M8 19h13"}),
  ],
  RaftGlyph.columns2: [
    ("rect", {"width": "18", "height": "18", "x": "3", "y": "3", "rx": "2"}),
    ("path", {"d": "M12 3v18"}),
  ],
  RaftGlyph.circleUserRound: [
    ("path", {"d": "M18 20a6 6 0 0 0-12 0"}),
    ("circle", {"cx": "12", "cy": "10", "r": "4"}),
    ("circle", {"cx": "12", "cy": "12", "r": "10"}),
  ],
  RaftGlyph.laptop: [
    (
      "path",
      {
        "d": "M18 5a2 2 0 0 1 2 2v8.526a2 2 0 0 0 .212.897l1.068 2.127a1 1 0 0 1-.9 1.45H3.62a1 1 0 0 1-.9-1.45l1.068-2.127A2 2 0 0 0 4 15.526V7a2 2 0 0 1 2-2z",
      },
    ),
    ("path", {"d": "M20.054 15.987H3.946"}),
  ],
  RaftGlyph.loaderCircle: [
    ("path", {"d": "M21 12a9 9 0 1 1-6.219-8.56"}),
  ],
  RaftGlyph.ban: [
    ("circle", {"cx": "12", "cy": "12", "r": "10"}),
    ("path", {"d": "M4.929 4.929 19.07 19.071"}),
  ],
};

/// Compatibility bridge for existing app call sites. Known symbols use the
/// same Lucide geometry as Web; unsupported app-specific icons remain explicit.
class RaftSymbol extends StatelessWidget {
  const RaftSymbol(this.icon, {super.key, this.size = 18, this.color});
  final IconData icon;
  final double size;
  final Color? color;
  @override
  Widget build(BuildContext context) {
    final glyph = raftGlyphForMaterialIcon(icon);
    return glyph == null
        ? Icon(icon, size: size, color: color)
        : RaftIcon(glyph, size: size, color: color);
  }
}

RaftGlyph? raftGlyphForMaterialIcon(IconData icon) => {
  Icons.send: RaftGlyph.send,
  Icons.send_outlined: RaftGlyph.send,
  Icons.arrow_upward: RaftGlyph.arrowUp,
  Icons.add: RaftGlyph.plus,
  Icons.attach_file: RaftGlyph.paperclip,
  Icons.image: RaftGlyph.image,
  Icons.image_outlined: RaftGlyph.image,
  Icons.chevron_right: RaftGlyph.chevronRight,
  Icons.chevron_left: RaftGlyph.chevronLeft,
  Icons.keyboard_arrow_down: RaftGlyph.chevronDown,
  Icons.expand_more: RaftGlyph.chevronDown,
  Icons.check: RaftGlyph.check,
  Icons.close: RaftGlyph.x,
  Icons.more_horiz: RaftGlyph.ellipsis,
  Icons.more_vert: RaftGlyph.ellipsis,
  Icons.forum_outlined: RaftGlyph.messageSquare,
  Icons.chat_bubble_outline: RaftGlyph.messageSquare,
  Icons.circle_outlined: RaftGlyph.circle,
  Icons.check_circle_outline: RaftGlyph.circleCheck,
  Icons.reply: RaftGlyph.reply,
  Icons.description_outlined: RaftGlyph.fileText,
  Icons.delete_outline: RaftGlyph.trash2,
  Icons.download: RaftGlyph.download,
  Icons.copy: RaftGlyph.copy,
  Icons.visibility: RaftGlyph.eye,
  Icons.visibility_outlined: RaftGlyph.eye,
  Icons.visibility_off: RaftGlyph.eyeOff,
  Icons.search: RaftGlyph.search,
  Icons.settings: RaftGlyph.settings,
  Icons.settings_outlined: RaftGlyph.settings,
  Icons.person_outline: RaftGlyph.user,
  Icons.people_outline: RaftGlyph.users,
  Icons.smart_toy_outlined: RaftGlyph.bot,
  Icons.computer: RaftGlyph.monitor,
  Icons.bookmark_outline: RaftGlyph.bookmark,
  Icons.tag: RaftGlyph.hash,
  Icons.lock_outline: RaftGlyph.lock,
  Icons.link: RaftGlyph.link,
  Icons.menu: RaftGlyph.menu,
  Icons.open_in_new: RaftGlyph.externalLink,
  Icons.refresh: RaftGlyph.refreshCw,
  Icons.arrow_back: RaftGlyph.arrowLeft,
  Icons.play_arrow_outlined: RaftGlyph.play,
  Icons.pause: RaftGlyph.pause,
  Icons.block: RaftGlyph.ban,
  Icons.done_all: RaftGlyph.checkCheck,
}[icon];
