import 'dart:ui' as ui;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:raft_ui/src/avatar_content.dart';
import 'package:raft_ui/src/avatar_pixel_data.dart';

class _FrameControl extends ImageStreamCompleter {
  void deliver(ImageInfo frame) => setImage(frame);
}

class _ControlledProvider extends ImageProvider<_ControlledProvider> {
  _ControlledProvider(this.control);
  final _FrameControl control;
  @override
  Future<_ControlledProvider> obtainKey(ImageConfiguration configuration) =>
      SynchronousFuture(this);
  @override
  ImageStreamCompleter loadImage(
    _ControlledProvider key,
    ImageDecoderCallback decode,
  ) => control;
}

Future<ui.Image> _image(WidgetTester tester, Color color) async {
  return (await tester.runAsync(() async {
    final recorder = ui.PictureRecorder();
    Canvas(recorder)
        .drawRect(const Rect.fromLTWH(0, 0, 8, 8), Paint()..color = color);
    final picture = recorder.endRecording();
    try {
      return await picture.toImage(8, 8);
    } finally {
      picture.dispose();
    }
  }))!;
}

Widget frame(RaftAvatarContent content) => MaterialApp(
  home: Center(child: SizedBox.square(dimension: 36, child: content)),
);
const uploadedA = 'https://public.example.test/api/avatars/users/abcdef.webp';
const uploadedB = 'https://public.example.test/api/avatars/users/123456.webp';
const gravatar = 'https://www.gravatar.com/avatar/public-test-hash?s=80&d=404';
const fallback = ColoredBox(key: Key('clean-placeholder'), color: Colors.grey);

void main() {
  test('canonical preset palette and every eight-by-eight row stay valid', () {
    expect(raftPixelAvatarPresets.length, 18);
    expect(raftDefaultPixelAvatarKey, 'robot');
    for (final preset in raftPixelAvatarPresets.values) {
      expect(preset.rows.length, 8);
      for (final row in preset.rows) {
        expect(row.length, 8);
        expect(row.split('').every(raftPixelAvatarPalette.containsKey), isTrue);
      }
    }
    expect(raftPixelAvatarData('unknown-key'), isNull);
    expect(raftPixelAvatarData('mug')!.background, '#F8EEDF');
  });
  test('random output matches actual transpiled source including UTF16 astral seeds', () {
    // Generated by derive-source-vectors.cjs from the pinned TS function, not native code.
    const source = <String, (String, List<String>)>{
      '': (
        '#FE7DA8',
        [
          'WWW__WWW',
          '________',
          '_WW__WW_',
          'W______W',
          '__WWWW__',
          '_WW__WW_',
          '___WW___',
          'W__WW__W',
        ],
      ),
      'public-seed': (
        '#BBAFE6',
        [
          'K______K',
          '___KK___',
          '________',
          '_K_KK_K_',
          'K_K__K_K',
          'K_K__K_K',
          'K__KK__K',
          'K_KKKK_K',
        ],
      ),
      'Cody': (
        '#1E1E1C',
        [
          '___CC___',
          '________',
          '_CC__CC_',
          '_CC__CC_',
          'CC____CC',
          '________',
          '__CCCC__',
          'CCC__CCC',
        ],
      ),
      'seed:with:colons': (
        '#FE7DA8',
        [
          '_WW__WW_',
          '________',
          '________',
          'W__WW__W',
          'W_W__W_W',
          'W__WW__W',
          'WWWWWWWW',
          'WWWWWWWW',
        ],
      ),
      '日本語': (
        '#A9D877',
        [
          '_K____K_',
          '_KK__KK_',
          'KK____KK',
          'KKK__KKK',
          '__KKKK__',
          'KK_KK_KK',
          'KK____KK',
          'KK____KK',
        ],
      ),
      '😀': (
        '#1E1E1C',
        [
          'CC____CC',
          'CC_CC_CC',
          'CCCCCCCC',
          '_C____C_',
          'C_CCCC_C',
          'CC_CC_CC',
          '_CCCCCC_',
          'CCCCCCCC',
        ],
      ),
      '𐐷': (
        '#BBAFE6',
        [
          '_K____K_',
          '__KKKK__',
          '__K__K__',
          '_K____K_',
          'KK_KK_KK',
          'K_K__K_K',
          'K_K__K_K',
          'K__KK__K',
        ],
      ),
    };
    for (final entry in source.entries) {
      final actual = raftPixelAvatarData('random:${entry.key}')!;
      expect(actual.background, entry.value.$1, reason: entry.key);
      expect(actual.rows, entry.value.$2, reason: entry.key);
      expect(
        actual.rows.every((row) => row == row.split('').reversed.join()),
        isTrue,
      );
    }
  });
  test('only uploaded source human path preempts Gravatar', () {
    for (final url in [
      uploadedA,
      '/avatars/users/abcdef.webp',
      '/api/avatars/users/ABCDEF.webp',
    ]) {
      expect(RaftAvatarContent.isUploadedHumanAvatar(url), isTrue);
    }
    for (final url in [
      'https://provider.example.test/profile.webp',
      '/api/avatars/agents/abcdef.webp',
      '/api/attachments/a',
      'pixel:mug',
    ]) {
      expect(RaftAvatarContent.isUploadedHumanAvatar(url), isFalse);
    }
  });
  testWidgets(
    'uploaded pending stays clean; failed upload falls through to decoded Gravatar',
    (tester) async {
      final upload = _FrameControl(), hash = _FrameControl();
      final providers = {
        uploadedA: _ControlledProvider(upload),
        gravatar: _ControlledProvider(hash),
      };
      final requested = <String>[];
      await tester.pumpWidget(
        frame(
          RaftAvatarContent(
            name: 'Public human',
            uploadedUrl: uploadedA,
            gravatarUrl: gravatar,
            fallback: fallback,
            imageProviderBuilder: (url) {
              requested.add(url);
              return providers[url]!;
            },
          ),
        ),
      );
      expect(requested, [uploadedA]);
      expect(find.byKey(const Key('clean-placeholder')), findsOneWidget);
      upload.reportError(
        exception: StateError('public uploaded fixture failed'),
        stack: StackTrace.current,
      );
      await tester.pump();
      expect(requested, [uploadedA, gravatar]);
      expect(find.byKey(const Key('clean-placeholder')), findsOneWidget);
      hash.deliver(ImageInfo(image: await _image(tester, Colors.blue)));
      await tester.pump();
      expect(find.byKey(const Key('clean-placeholder')), findsNothing);
      expect(tester.widget<RawImage>(find.byType(RawImage)).image!.width, 8);
      await tester.pumpWidget(const SizedBox.shrink());
    },
  );
  testWidgets(
    'provider URL never preempts Gravatar and Gravatar failure returns placeholder',
    (tester) async {
      final control = _FrameControl();
      final calls = <String>[];
      await tester.pumpWidget(
        frame(
          RaftAvatarContent(
            name: 'Public human',
            uploadedUrl: 'https://provider.example.test/default.webp',
            gravatarUrl: gravatar,
            fallback: fallback,
            imageProviderBuilder: (url) {
              calls.add(url);
              return _ControlledProvider(control);
            },
          ),
        ),
      );
      expect(calls, [gravatar]);
      control.reportError(
        exception: StateError('public404 fixture'),
        stack: StackTrace.current,
      );
      await tester.pump();
      expect(find.byKey(const Key('clean-placeholder')), findsOneWidget);
      expect(find.byType(RawImage), findsNothing);
    },
  );
  testWidgets('delayed former identity frame cannot replace current identity', (
    tester,
  ) async {
    final a = _FrameControl(), b = _FrameControl();
    final providers = {
      uploadedA: _ControlledProvider(a),
      uploadedB: _ControlledProvider(b),
    };
    Widget person(String url) => frame(
      RaftAvatarContent(
        name: 'Public human',
        uploadedUrl: url,
        fallback: fallback,
        imageProviderBuilder: (url) => providers[url]!,
      ),
    );
    await tester.pumpWidget(person(uploadedA));
    await tester.pumpWidget(person(uploadedB));
    a.deliver(ImageInfo(image: await _image(tester, Colors.red)));
    await tester.pump();
    expect(find.byKey(const Key('clean-placeholder')), findsOneWidget);
    expect(find.byType(RawImage), findsNothing);
    b.deliver(ImageInfo(image: await _image(tester, Colors.blue)));
    await tester.pump();
    expect(tester.widget<RawImage>(find.byType(RawImage)).image!.width, 8);
    await tester.pumpWidget(const SizedBox.shrink());
  });
  testWidgets(
    'agent custom failure shows exact pixel preset without human placeholder',
    (tester) async {
      final control = _FrameControl();
      await tester.pumpWidget(
        frame(
          RaftAvatarContent(
            name: 'Public agent',
            kind: RaftAvatarContentKind.agent,
            uploadedUrl:
                'https://public.example.test/api/avatars/agents/abcdef.webp',
            pixelKey: 'mug',
            imageProviderBuilder: (_) => _ControlledProvider(control),
          ),
        ),
      );
      expect(find.byType(RaftPixelAvatar), findsOneWidget);
      control.reportError(
        exception: StateError('public custom fixture failed'),
        stack: StackTrace.current,
      );
      await tester.pump();
      expect(
        tester.widget<RaftPixelAvatar>(find.byType(RaftPixelAvatar)).avatarKey,
        'mug',
      );
      expect(
        find.byType(Image),
        findsOneWidget,
      ); // failed image owns the error fallback subtree
    },
  );
  testWidgets(
    'pixel agents make no network provider; invalid key stays source-empty',
    (tester) async {
      var requests = 0;
      await tester.pumpWidget(
        frame(
          RaftAvatarContent(
            name: 'Public agent',
            kind: RaftAvatarContentKind.agent,
            pixelKey: 'random:public-seed',
            imageProviderBuilder: (_) {
              requests++;
              throw StateError('must not request');
            },
          ),
        ),
      );
      expect(requests, 0);
      expect(find.byType(CustomPaint), findsWidgets);
      await tester.pumpWidget(
        frame(
          const RaftAvatarContent(
            name: 'Public agent',
            kind: RaftAvatarContentKind.agent,
            pixelKey: 'invalid-key',
          ),
        ),
      );
      expect(find.byType(Image), findsNothing);
    },
  );
  testWidgets(
    'no public image data, unsafe URL, or no hash uses clean fallback',
    (tester) async {
      for (final url in [
        null,
        'file:///private/avatar',
        'https://user:password@example.test/api/avatars/users/abcdef.webp',
      ]) {
        var requests = 0;
        await tester.pumpWidget(
          frame(
            RaftAvatarContent(
              name: 'Public human',
              uploadedUrl: url,
              fallback: fallback,
              imageProviderBuilder: (_) {
                requests++;
                throw StateError('must not request');
              },
            ),
          ),
        );
        expect(requests, 0);
        expect(find.byKey(const Key('clean-placeholder')), findsOneWidget);
      }
    },
  );
}
