// Human readable per-component recipe tables (docs/component-recipes.md).
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname } from 'node:path';
import { displayValue } from './cascade.mjs';

const MAX_CELL = 160;
const cell = (s) => {
  let t = String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
  if (t.length > MAX_CELL) t = `${t.slice(0, MAX_CELL - 1)}…`;
  return t;
};
const kv = (obj) => Object.entries(obj).map(([k, v]) => `${k}: ${displayValue(v)}`);

function comboKey(axes, props) {
  return axes.map((a) => `${a.key}=${props[a.key] ?? '∅'}`).join('&');
}

export function writeDocs(path, model, coverage) {
  const L = [];
  L.push('# Component recipes (generated)');
  L.push('');
  L.push('GENERATED by `tool/recipes/run` from raft-ui ' +
    `${model.source.version} (\`dist/index.mjs\` sha256 \`${model.source.sha256.slice(0, 12)}\`) with tailwindcss ${model.source.tailwindcss}. Do not edit.`);
  L.push('');
  L.push(`Tailwind input CSS: \`${model.source.inputCss.trim().replace(/\n/g, ' ')}\`` +
    (model.source.webThemeSha256 ? ' (`raft-web-theme.css` = the Web client\'s `@theme` overrides, `tool/recipes/web-theme.css`).' : '.'));
  L.push('');
  L.push('Every `tv()` recipe is evaluated with the real tailwind-variants + raft-ui `cn` (tailwind-merge) for every variant');
  L.push('combination, and every resulting class is compiled by Tailwind v4 with raft-ui `styles.css` as input. Values below are');
  L.push('after cascade and `var()` resolution: lengths in logical px, `token(x)` = foundation token `--x` in lowerCamelCase');
  L.push('(resolved per theme at runtime), literal colours as `#AARRGGBB`. State rows show only properties that change.');
  L.push('Authoritative data: `build/recipes/recipes.json`; Dart: `packages/raft_ui/lib/src/recipes/`.');
  L.push('');
  L.push('## Coverage');
  L.push('');
  L.push(`- Recipes: ${model.recipes.length}; variant combinations: ${model.recipes.reduce((n, r) => n + r.combos.length, 0)}`);
  L.push(`- Distinct classes in recipe sources: ${coverage.classesInRecipes}`);
  for (const [k, v] of Object.entries(coverage.counts)) L.push(`  - ${k}: ${v}`);
  if (coverage.noCss.length) {
    L.push('');
    L.push('Classes for which Tailwind emits no CSS (inert on the Web as well):');
    L.push('');
    for (const n of coverage.noCss) L.push(`- \`${n.class}\` (${n.recipes.join(', ')}): ${n.reason ?? 'UNEXPLAINED'}`);
  }
  L.push('');
  L.push('## Index');
  L.push('');
  for (const r of model.recipes) L.push(`- [${r.name}](#${r.name.toLowerCase().replace(/\$/g, '')}) → \`${r.dartClass}\``);
  L.push('');

  for (const r of model.recipes) {
    L.push(`## ${r.name}`);
    L.push('');
    L.push(`Dart: \`${r.dartClass}\` · source: \`${r.region}\` (index.mjs:${r.line})${r.extends ? ` · extends \`${r.extends}\`` : ''}`);
    if (r.exportedComponents.length) L.push(`· components: ${r.exportedComponents.map((c) => `\`${c}\``).join(', ')}`);
    L.push('');
    if (r.axes.length) {
      L.push('| axis | values | default |');
      L.push('|---|---|---|');
      for (const a of r.axes) L.push(`| ${a.key} | ${a.values.map(cell).join(' · ')} | ${a.default ?? (a.allowsUnset ? '(unset)' : '—')} |`);
      L.push('');
    }
    const themeAxis = r.axes.find((a) => a.key === 'theme');
    const columns = themeAxis ? themeAxis.values : [null];
    const byKey = new Map(r.combos.map((c) => [comboKey(r.axes, c.props), c]));
    const defaultProps = (overrides) => {
      const p = {};
      for (const a of r.axes) p[a.key] = a.default ?? (a.allowsUnset ? null : a.values[0]);
      return { ...p, ...overrides };
    };
    const comboFor = (overrides) => byKey.get(comboKey(r.axes, defaultProps(overrides)));
    const colCombos = columns.map((t) => comboFor(t ? { theme: t } : {}));
    const header = themeAxis ? columns : ['value'];
    const defaultsDesc = r.axes.filter((a) => a.key !== 'theme').map((a) => `${a.key}=${a.default ?? '∅'}`).join(', ');
    L.push(`### Default${defaultsDesc ? ` (${defaultsDesc})` : ''}`);
    L.push('');
    L.push(`| slot | target | property | ${header.join(' | ')} |`);
    L.push(`|---|---|---|${header.map(() => '---').join('|')}|`);
    for (const slot of r.slots) {
      const resolvedCols = colCombos.map((c) => model.resolved[c.slots[slot]]);
      const targets = [...new Set(resolvedCols.flatMap((x) => Object.keys(x)))];
      for (const target of targets) {
        const props = [...new Set(resolvedCols.flatMap((x) => Object.keys(x[target]?.base ?? {})))];
        for (const p of props) {
          L.push(`| ${slot} | ${cell(target)} | ${p} | ${resolvedCols.map((x) => cell(displayValue(x[target]?.base?.[p]))).join(' | ')} |`);
        }
        const states = [...new Set(resolvedCols.flatMap((x) => Object.keys(x[target]?.states ?? {})))];
        for (const st of states) {
          L.push(`| ${slot} | ${cell(target)} | **${cell(st)}** | ${resolvedCols.map((x) => cell(kv(x[target]?.states?.[st] ?? {}).join('; ') || '·')).join(' | ')} |`);
        }
      }
    }
    L.push('');
    const deltaRows = [];
    for (const a of r.axes) {
      if (a.key === 'theme') continue;
      const opts = a.allowsUnset ? [null, ...a.values] : a.values;
      for (const v of opts) {
        if (v === (a.default ?? (a.allowsUnset ? null : a.values[0]))) continue;
        for (const slot of r.slots) {
          const cells = columns.map((t, i) => {
            const base = colCombos[i];
            const c = comboFor({ ...(t ? { theme: t } : {}), [a.key]: v });
            if (!c || c.slots[slot] === base.slots[slot]) return null;
            const x = model.resolved[base.slots[slot]];
            const y = model.resolved[c.slots[slot]];
            const parts = [];
            for (const target of new Set([...Object.keys(x), ...Object.keys(y)])) {
              const pre = target === 'self' ? '' : `${target} `;
              const bx = x[target]?.base ?? {};
              const by = y[target]?.base ?? {};
              for (const k of new Set([...Object.keys(bx), ...Object.keys(by)])) {
                if (JSON.stringify(bx[k]) !== JSON.stringify(by[k])) parts.push(`${pre}${k}: ${displayValue(by[k])}`);
              }
              const sx = x[target]?.states ?? {};
              const sy = y[target]?.states ?? {};
              for (const st of new Set([...Object.keys(sx), ...Object.keys(sy)])) {
                if (JSON.stringify(sx[st]) !== JSON.stringify(sy[st])) parts.push(`${pre}[${st}] ${kv(sy[st] ?? {}).join(', ') || '(none)'}`);
              }
            }
            return parts.join('; ') || '(classes differ, same result)';
          });
          if (cells.some(Boolean)) deltaRows.push(`| ${a.key}=${v ?? '∅'} | ${slot} | ${cells.map((x) => cell(x ?? '·')).join(' | ')} |`);
        }
      }
    }
    if (deltaRows.length) {
      L.push('### Variant deltas (one axis changed from the default)');
      L.push('');
      L.push(`| variant | slot | ${header.join(' | ')} |`);
      L.push(`|---|---|${header.map(() => '---').join('|')}|`);
      L.push(...deltaRows);
      L.push('');
    }
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, L.join('\n') + '\n');
}
